In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
dataset_path = "../dataset/raw"

csv_files = [f for f in os.listdir(dataset_path) if f.endswith(".csv")]

print(f"Total CSV files: {len(csv_files)}")
print("\n".join(sorted(csv_files)))

Total CSV files: 18
DrDoS_DNS.csv
DrDoS_LDAP.csv
DrDoS_MSSQL.csv
DrDoS_NTP.csv
DrDoS_NetBIOS.csv
DrDoS_SNMP.csv
DrDoS_SSDP.csv
DrDoS_UDP.csv
LDAP.csv
MSSQL.csv
NetBIOS.csv
Portmap.csv
Syn copy.csv
Syn.csv
TFTP.csv
UDP.csv
UDPLag copy.csv
UDPLag.csv

In [3]:
# Display all CSV files
for i, file in enumerate(sorted(csv_files), start=1):
    print(f"{i}. {file}")

1. DrDoS_DNS.csv
2. DrDoS_LDAP.csv
3. DrDoS_MSSQL.csv
4. DrDoS_NTP.csv
5. DrDoS_NetBIOS.csv
6. DrDoS_SNMP.csv
7. DrDoS_SSDP.csv
8. DrDoS_UDP.csv
9. LDAP.csv
10. MSSQL.csv
11. NetBIOS.csv
12. Portmap.csv
13. Syn copy.csv
14. Syn.csv
15. TFTP.csv
16. UDP.csv
17. UDPLag copy.csv
18. UDPLag.csv

In [4]:
import os

for file in sorted(csv_files):
    path = os.path.join(dataset_path, file)
    size_mb = os.path.getsize(path) / (1024 * 1024)
    print(f"{file:<20} {size_mb:.2f} MB")

DrDoS_DNS.csv        2034.48 MB
DrDoS_LDAP.csv       874.81 MB
DrDoS_MSSQL.csv      1801.66 MB
DrDoS_NTP.csv        615.13 MB
DrDoS_NetBIOS.csv    1618.84 MB
DrDoS_SNMP.csv       2071.93 MB
DrDoS_SSDP.csv       1194.65 MB
DrDoS_UDP.csv        1436.27 MB
LDAP.csv             831.03 MB
MSSQL.csv            2275.68 MB
NetBIOS.csv          1352.76 MB
Portmap.csv          74.97 MB
Syn copy.csv         607.79 MB
Syn.csv              1790.40 MB
TFTP.csv             8871.09 MB
UDP.csv              1709.74 MB
UDPLag copy.csv      150.65 MB
UDPLag.csv           304.98 MB

In [5]:
sample_file = os.path.join(dataset_path, csv_files[0])

df = pd.read_csv(sample_file, low_memory=False)

print(f"File: {csv_files[0]}")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

df.head()

File: DrDoS_NTP.csv
Rows: 1217007
Columns: 88

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,172.16.0.5-192.168.50.1-60675-80-6,172.16.0.5,60675,192.168.50.1,80,6,2018-12-01 09:17:11.183810,5220876,12,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,205.174.165.72/c.php,1,DrDoS_NTP
1,7,172.16.0.5-192.168.50.1-60676-80-6,172.16.0.5,60676,192.168.50.1,80,6,2018-12-01 09:17:11.205636,12644252,5,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_NTP
2,12858,192.168.50.7-65.55.163.78-50458-443-6,65.55.163.78,443,192.168.50.7,50458,6,2018-12-01 09:17:12.634569,3,2,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,BENIGN
3,10191,192.168.50.7-65.55.163.78-50465-443-6,65.55.163.78,443,192.168.50.7,50465,6,2018-12-01 09:17:13.458370,3,2,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,BENIGN
4,239,192.168.50.253-224.0.0.5-0-0-0,192.168.50.253,0,224.0.0.5,0,0,2018-12-01 09:17:13.470913,114329232,52,...,2.466441,15.0,6.0,9527428.0,248706.681286,9950741.0,9092248.0,0,0,BENIGN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1217007 entries, 0 to 1217006
Data columns (total 88 columns):
 #   Column                        Non-Null Count    Dtype
---  ------                        --------------    -----
 0   Unnamed: 0                    1217007 non-null  int64
 1   Flow ID                       1217007 non-null  object
 2    Source IP                    1217007 non-null  object
 3    Source Port                  1217007 non-null  int64
 4    Destination IP               1217007 non-null  object
 5    Destination Port             1217007 non-null  int64
 6    Protocol                     1217007 non-null  int64
 7    Timestamp                    1217007 non-null  object
 8    Flow Duration                1217007 non-null  int64
 9    Total Fwd Packets            1217007 non-null  int64
 10   Total Backward Packets       1217007 non-null  int64
 11  Total Length of Fwd Packets   1217007 non-null  float64
 12   Total Length of Bwd Packets  1217007 non-null  float64
 13   Fwd Packet Length Max        1217007 non-null  float64
 14   Fwd Packet Length Min        1217007 non-null  float64
 15   Fwd Packet Length Mean       1217007 non-null  float64
 16   Fwd Packet Length Std        1217007 non-null  float64
 17  Bwd Packet Length Max         1217007 non-null  float64
 18   Bwd Packet Length Min        1217007 non-null  float64
 19   Bwd Packet Length Mean       1217007 non-null  float64
 20   Bwd Packet Length Std        1217007 non-null  float64
 21  Flow Bytes/s                  1216976 non-null  float64
 22   Flow Packets/s               1217007 non-null  float64
 23   Flow IAT Mean                1217007 non-null  float64
 24   Flow IAT Std                 1217007 non-null  float64
 25   Flow IAT Max                 1217007 non-null  float64
 26   Flow IAT Min                 1217007 non-null  float64
 27  Fwd IAT Total                 1217007 non-null  float64
 28   Fwd IAT Mean                 1217007 non-null  float64
 29   Fwd IAT Std                  1217007 non-null  float64
 30   Fwd IAT Max                  1217007 non-null  float64
 31   Fwd IAT Min                  1217007 non-null  float64
 32  Bwd IAT Total                 1217007 non-null  float64
 33   Bwd IAT Mean                 1217007 non-null  float64
 34   Bwd IAT Std                  1217007 non-null  float64
 35   Bwd IAT Max                  1217007 non-null  float64
 36   Bwd IAT Min                  1217007 non-null  float64
 37  Fwd PSH Flags                 1217007 non-null  int64
 38   Bwd PSH Flags                1217007 non-null  int64
 39   Fwd URG Flags                1217007 non-null  int64
 40   Bwd URG Flags                1217007 non-null  int64
 41   Fwd Header Length            1217007 non-null  int64
 42   Bwd Header Length            1217007 non-null  int64
 43  Fwd Packets/s                 1217007 non-null  float64
 44   Bwd Packets/s                1217007 non-null  float64
 45   Min Packet Length            1217007 non-null  float64
 46   Max Packet Length            1217007 non-null  float64
 47   Packet Length Mean           1217007 non-null  float64
 48   Packet Length Std            1217007 non-null  float64
 49   Packet Length Variance       1217007 non-null  float64
 50  FIN Flag Count                1217007 non-null  int64
 51   SYN Flag Count               1217007 non-null  int64
 52   RST Flag Count               1217007 non-null  int64
 53   PSH Flag Count               1217007 non-null  int64
 54   ACK Flag Count               1217007 non-null  int64
 55   URG Flag Count               1217007 non-null  int64
 56   CWE Flag Count               1217007 non-null  int64
 57   ECE Flag Count               1217007 non-null  int64
 58   Down/Up Ratio                1217007 non-null  float64
 59   Average Packet Size          1217007 non-null  float64
 60   Avg Fwd Segment Size         1217007 non-null  float64
 61   Avg Bwd Segment Size         1217007 non-null  float64
 62   Fwd Header Length.1          1217007 non-null  int64
 63  Fwd Avg Bytes/Bulk            1217007 non-null  int64
 64   Fwd Avg Packets/Bulk         1217007 non-null  int64
 65   Fwd Avg Bulk Rate            1217007 non-null  int64
 66   Bwd Avg Bytes/Bulk           1217007 non-null  int64
 67   Bwd Avg Packets/Bulk         1217007 non-null  int64
 68  Bwd Avg Bulk Rate             1217007 non-null  int64
 69  Subflow Fwd Packets           1217007 non-null  int64
 70   Subflow Fwd Bytes            1217007 non-null  int64
 71   Subflow Bwd Packets          1217007 non-null  int64
 72   Subflow Bwd Bytes            1217007 non-null  int64
 73  Init_Win_bytes_forward        1217007 non-null  int64
 74   Init_Win_bytes_backward      1217007 non-null  int64
 75   act_data_pkt_fwd             1217007 non-null  int64
 76   min_seg_size_forward         1217007 non-null  int64
 77  Active Mean                   1217007 non-null  float64
 78   Active Std                   1217007 non-null  float64
 79   Active Max                   1217007 non-null  float64
 80   Active Min                   1217007 non-null  float64
 81  Idle Mean                     1217007 non-null  float64
 82   Idle Std                     1217007 non-null  float64
 83   Idle Max                     1217007 non-null  float64
 84   Idle Min                     1217007 non-null  float64
 85  SimillarHTTP                  1217007 non-null  object
 86   Inbound                      1217007 non-null  int64
 87   Label                        1217007 non-null  object
dtypes: float64(45), int64(37), object(6)
memory usage: 817.1+ MB

In [9]:
df.columns = df.columns.str.strip()

In [10]:
df["Label"].value_counts()

Label
DrDoS_NTP    1202642
BENIGN         14365
Name: count, dtype: int64

In [11]:
# Missing values
print("Missing values:", df.isnull().sum().sum())

# Infinite values
print("Infinite values:", np.isinf(df.select_dtypes(include=[np.number])).sum().sum())

Missing values: 31
Infinite values: 14061

In [12]:
missing = df.isnull().sum()
missing = missing[missing > 0]

print(missing)

Flow Bytes/s    31
dtype: int64

In [13]:
# Rows with missing values
df[df["Flow Bytes/s"].isnull()].head()

# Rows with infinite values
df[np.isinf(df["Flow Bytes/s"])].head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
832,330,192.168.50.6-209.85.232.108-56155-465-6,192.168.50.6,56155,209.85.232.108,465,6,2018-12-01 09:19:48.982733,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
1341,564,192.168.50.7-216.58.219.234-50613-443-6,192.168.50.7,50613,216.58.219.234,443,6,2018-12-01 09:21:58.116223,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
1852,799,192.168.50.6-74.125.28.94-56138-443-6,192.168.50.6,56138,74.125.28.94,443,6,2018-12-01 09:22:34.046300,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
2472,1109,172.217.3.97-192.168.50.6-443-56205-6,192.168.50.6,56205,172.217.3.97,443,6,2018-12-01 09:23:36.619744,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN
3072,1365,172.217.10.234-192.168.50.6-443-56216-6,192.168.50.6,56216,172.217.10.234,443,6,2018-12-01 09:26:27.517317,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,BENIGN

In [14]:
print(df.describe())

/Users/apple/Library/Python/3.9/lib/python/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
/Users/apple/Library/Python/3.9/lib/python/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

         Unnamed: 0   Source Port  Destination Port      Protocol  \
count  1.217007e+06  1.217007e+06      1.217007e+06  1.217007e+06
mean   3.258309e+03  1.360350e+03      3.251510e+04  1.688341e+01
std    2.008943e+03  5.762652e+03      1.911544e+04  1.141547e+00
min    0.000000e+00  0.000000e+00      0.000000e+00  0.000000e+00
25%    1.592000e+03  6.340000e+02      1.595600e+04  1.700000e+01
50%    3.191000e+03  7.220000e+02      3.253400e+04  1.700000e+01
75%    4.815000e+03  8.760000e+02      4.912000e+04  1.700000e+01
max    1.588300e+04  6.553200e+04      6.553500e+04  1.700000e+01

       Flow Duration  Total Fwd Packets  Total Backward Packets  \
count   1.217007e+06       1.217007e+06            1.217007e+06
mean    1.314029e+05       6.315746e+01            1.140297e-01
std     3.442526e+06       6.368370e+01            5.989404e+00
min     0.000000e+00       1.000000e+00            0.000000e+00
25%     3.500000e+02       1.400000e+01            0.000000e+00
50%     1.001000e+03       3.900000e+01            0.000000e+00
75%     4.296000e+03       9.400000e+01            0.000000e+00
max     1.199999e+08       9.160000e+02            1.862000e+03

       Total Length of Fwd Packets  Total Length of Bwd Packets  \
count                 1.217007e+06                 1.217007e+06
mean                  2.758204e+04                 1.324724e+02
std                   2.811284e+04                 2.097989e+04
min                   0.000000e+00                 0.000000e+00
25%                   5.280000e+03                 0.000000e+00
50%                   1.672000e+04                 0.000000e+00
75%                   4.136000e+04                 0.000000e+00
max                   1.760000e+05                 8.829488e+06

       Fwd Packet Length Max  ...  min_seg_size_forward   Active Mean  \
count           1.217007e+06  ...          1.217007e+06  1.217007e+06
mean            4.320774e+02  ...         -8.383064e+06  1.051678e+03
std             6.799413e+01  ...          9.406053e+07  6.693206e+04
min             0.000000e+00  ...         -1.408238e+09  0.000000e+00
25%             4.400000e+02  ...         -1.000000e+00  0.000000e+00
50%             4.400000e+02  ...          8.000000e+00  0.000000e+00
75%             4.400000e+02  ...          2.000000e+01  0.000000e+00
max             3.569000e+03  ...          4.400000e+02  1.721664e+07

         Active Std    Active Max    Active Min     Idle Mean      Idle Std  \
count  1.217007e+06  1.217007e+06  1.217007e+06  1.217007e+06  1.217007e+06
mean   3.300205e+02  1.482967e+03  8.418789e+02  4.151085e+04  2.718502e+03
std    2.301964e+04  8.194273e+04  6.370605e+04  1.419061e+06  2.421458e+05
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
max    1.100562e+07  1.941638e+07  1.721664e+07  1.147455e+08  5.072577e+07

           Idle Max      Idle Min       Inbound
count  1.217007e+06  1.217007e+06  1.217007e+06
mean   4.397031e+04  3.920079e+04  9.886311e-01
std    1.490299e+06  1.380248e+06  1.060171e-01
min    0.000000e+00  0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00  1.000000e+00
50%    0.000000e+00  0.000000e+00  1.000000e+00
75%    0.000000e+00  0.000000e+00  1.000000e+00
max    1.147455e+08  1.147455e+08  1.000000e+00

[8 rows x 82 columns]

In [15]:
column_sets = {}

for file in csv_files:
    path = os.path.join(dataset_path, file)
    temp_df = pd.read_csv(path, nrows=0, low_memory=False)
    temp_df.columns = temp_df.columns.str.strip()
    column_sets[file] = list(temp_df.columns)

reference = column_sets[csv_files[0]]

all_same = True

for file, cols in column_sets.items():
    if cols != reference:
        print(f"{file} has different columns.")
        all_same = False

if all_same:
    print("✅ All CSV files have the same columns.")

✅ All CSV files have the same columns.

In [16]:
for file in sorted(csv_files):
    path = os.path.join(dataset_path, file)
    temp_df = pd.read_csv(path, usecols=[" Label"], low_memory=False)
    temp_df.columns = temp_df.columns.str.strip()

    labels = temp_df["Label"].unique()
    print(f"{file}: {labels}")

DrDoS_DNS.csv: ['DrDoS_DNS' 'BENIGN']
DrDoS_LDAP.csv: ['DrDoS_LDAP' 'BENIGN']
DrDoS_MSSQL.csv: ['DrDoS_MSSQL' 'BENIGN']
DrDoS_NTP.csv: ['DrDoS_NTP' 'BENIGN']
DrDoS_NetBIOS.csv: ['DrDoS_NetBIOS' 'BENIGN']
DrDoS_SNMP.csv: ['DrDoS_SNMP' 'BENIGN']
DrDoS_SSDP.csv: ['DrDoS_SSDP' 'BENIGN']
DrDoS_UDP.csv: ['DrDoS_UDP' 'BENIGN']
LDAP.csv: ['NetBIOS' 'BENIGN' 'LDAP']
MSSQL.csv: ['LDAP' 'BENIGN' 'MSSQL']
NetBIOS.csv: ['NetBIOS' 'BENIGN']
Portmap.csv: ['BENIGN' 'Portmap']
Syn copy.csv: ['Syn' 'BENIGN']
Syn.csv: ['Syn' 'BENIGN']
TFTP.csv: ['TFTP' 'BENIGN']
UDP.csv: ['MSSQL' 'BENIGN' 'UDP']
UDPLag copy.csv: ['UDP-lag' 'BENIGN' 'WebDDoS']
UDPLag.csv: ['UDP' 'BENIGN' 'UDPLag' 'Syn']

In [17]:
for file in sorted(csv_files):
    path = os.path.join(dataset_path, file)
    rows = sum(1 for _ in open(path)) - 1  # exclude header
    print(f"{file:<20} {rows:,} rows")

DrDoS_DNS.csv        5,074,413 rows
DrDoS_LDAP.csv       2,181,542 rows
DrDoS_MSSQL.csv      4,524,498 rows
DrDoS_NTP.csv        1,217,007 rows
DrDoS_NetBIOS.csv    4,094,986 rows
DrDoS_SNMP.csv       5,161,377 rows
DrDoS_SSDP.csv       2,611,374 rows
DrDoS_UDP.csv        3,136,802 rows
LDAP.csv             2,113,234 rows
MSSQL.csv            5,775,786 rows
NetBIOS.csv          3,455,899 rows
Portmap.csv          191,694 rows
Syn copy.csv         1,582,681 rows
Syn.csv              4,320,541 rows
TFTP.csv             20,107,827 rows
UDP.csv              3,782,206 rows
UDPLag copy.csv      370,605 rows
UDPLag.csv           725,165 rows

In [18]:
for file in sorted(csv_files):
    path = os.path.join(dataset_path, file)
    temp_df = pd.read_csv(path, nrows=100, low_memory=False)
    temp_df.columns = temp_df.columns.str.strip()

    print(f"\n{file}")
    print(temp_df.dtypes.value_counts())

DrDoS_DNS.csv
float64    45
int64      37
object      6
Name: count, dtype: int64

DrDoS_LDAP.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

DrDoS_MSSQL.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

DrDoS_NTP.csv
float64    45
int64      37
object      6
Name: count, dtype: int64

DrDoS_NetBIOS.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

DrDoS_SNMP.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

DrDoS_SSDP.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

DrDoS_UDP.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

LDAP.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

MSSQL.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

NetBIOS.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

Portmap.csv
float64    45
int64      37
object      6
Name: count, dtype: int64

Syn copy.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

Syn.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

TFTP.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

UDP.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

UDPLag copy.csv
float64    45
int64      38
object      5
Name: count, dtype: int64

UDPLag.csv
float64    45
int64      38
object      5
Name: count, dtype: int64