# Section 1

In [2]:
# =============================================================================
# SECTION 1 — ENVIRONMENT & PROJECT PATHS
# CELL 1 — Environment Setup and Project Paths
# =============================================================================

from pathlib import Path
import json
import pandas as pd
import numpy as np

# ---------------------------------------------------------------------------
# Project root
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path("/content/drive/MyDrive/Major_Project")

# ---------------------------------------------------------------------------
# Project directories
# ---------------------------------------------------------------------------

MITIGATION_DIR = PROJECT_ROOT / "mitigation"
EVALUATION_DIR = PROJECT_ROOT / "evaluation"
MODELS_DIR = PROJECT_ROOT / "models"

# Create mitigation directory if it does not already exist
MITIGATION_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Notebook 06 verified input artifacts
# ---------------------------------------------------------------------------

MITIGATION_INPUT_CSV = MITIGATION_DIR / "anomalyflow_test_results.csv"
MITIGATION_INPUT_SUMMARY = MITIGATION_DIR / "mitigation_input_summary.json"

# ---------------------------------------------------------------------------
# Notebook 06 frozen configuration
# ---------------------------------------------------------------------------

ANOMALYFLOW_CONFIG = EVALUATION_DIR / "anomalyflow_config.json"

# ---------------------------------------------------------------------------
# Display paths
# ---------------------------------------------------------------------------

print("=" * 80)
print("NOTEBOOK 07 — MITIGATION ENGINE")
print("=" * 80)

print("\nProject Root:")
print(PROJECT_ROOT)

print("\nInput Artifact:")
print(MITIGATION_INPUT_CSV)

print("\nInput Summary:")
print(MITIGATION_INPUT_SUMMARY)

print("\nAnomalyFlow Configuration:")
print(ANOMALYFLOW_CONFIG)

print("\nMitigation Output Directory:")
print(MITIGATION_DIR)

# ---------------------------------------------------------------------------
# Basic path verification
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("PATH VERIFICATION")
print("-" * 80)

print(f"Project root exists        : {PROJECT_ROOT.exists()}")
print(f"Input CSV exists           : {MITIGATION_INPUT_CSV.exists()}")
print(f"Input summary exists       : {MITIGATION_INPUT_SUMMARY.exists()}")
print(f"AnomalyFlow config exists  : {ANOMALYFLOW_CONFIG.exists()}")
print(f"Mitigation directory exists: {MITIGATION_DIR.exists()}")

================================================================================
NOTEBOOK 07 — MITIGATION ENGINE
================================================================================

Project Root:
/content/drive/MyDrive/Major_Project

Input Artifact:
/content/drive/MyDrive/Major_Project/mitigation/anomalyflow_test_results.csv

Input Summary:
/content/drive/MyDrive/Major_Project/mitigation/mitigation_input_summary.json

AnomalyFlow Configuration:
/content/drive/MyDrive/Major_Project/evaluation/anomalyflow_config.json

Mitigation Output Directory:
/content/drive/MyDrive/Major_Project/mitigation

--------------------------------------------------------------------------------
PATH VERIFICATION
--------------------------------------------------------------------------------
Project root exists        : True
Input CSV exists           : True
Input summary exists       : True
AnomalyFlow config exists  : False
Mitigation directory exists: True

In [3]:
# =============================================================================
# SECTION 1 — ENVIRONMENT & PROJECT PATHS
# CELL 2 — Verify Required Notebook 07 Input Artifacts
# =============================================================================

# Notebook 07 directly consumes the verified Notebook 06 sample-level artifact.
# No model retraining or reconstruction is required.

REQUIRED_INPUTS = {
    "Notebook 06 sample-level CSV": MITIGATION_INPUT_CSV,
    "Notebook 06 mitigation summary": MITIGATION_INPUT_SUMMARY,
}

print("=" * 80)
print("NOTEBOOK 07 INPUT ARTIFACT VERIFICATION")
print("=" * 80)

all_inputs_available = True

for artifact_name, artifact_path in REQUIRED_INPUTS.items():
    exists = artifact_path.exists()

    print(f"\n{artifact_name}")
    print(f"Path   : {artifact_path}")
    print(f"Exists : {exists}")

    if not exists:
        all_inputs_available = False

print("\n" + "-" * 80)
print(f"ALL REQUIRED INPUTS AVAILABLE : {all_inputs_available}")
print("-" * 80)

if not all_inputs_available:
    raise FileNotFoundError(
        "One or more required Notebook 06 mitigation artifacts are missing."
    )

print("\nNotebook 07 can proceed using the verified Notebook 06 artifacts.")

================================================================================
NOTEBOOK 07 INPUT ARTIFACT VERIFICATION
================================================================================

Notebook 06 sample-level CSV
Path   : /content/drive/MyDrive/Major_Project/mitigation/anomalyflow_test_results.csv
Exists : True

Notebook 06 mitigation summary
Path   : /content/drive/MyDrive/Major_Project/mitigation/mitigation_input_summary.json
Exists : True

--------------------------------------------------------------------------------
ALL REQUIRED INPUTS AVAILABLE : True
--------------------------------------------------------------------------------

Notebook 07 can proceed using the verified Notebook 06 artifacts.

# Section 2

In [4]:
# =============================================================================
# SECTION 2 — LOAD NOTEBOOK 06 ARTIFACT
# CELL 1 — Load Verified Sample-Level Mitigation Input
# =============================================================================

print("=" * 80)
print("LOADING NOTEBOOK 06 SAMPLE-LEVEL ARTIFACT")
print("=" * 80)

# ---------------------------------------------------------------------------
# Load verified Notebook 06 output
# ---------------------------------------------------------------------------

mitigation_df = pd.read_csv(MITIGATION_INPUT_CSV)

# ---------------------------------------------------------------------------
# Basic information
# ---------------------------------------------------------------------------

print("\nInput CSV loaded successfully.")

print(f"\nRows    : {len(mitigation_df):,}")
print(f"Columns : {len(mitigation_df.columns)}")

print("\nColumns:")
for i, column in enumerate(mitigation_df.columns, start=1):
    print(f"{i:2d}. {column}")

# ---------------------------------------------------------------------------
# Preview
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("FIRST 5 ROWS")
print("-" * 80)

display(mitigation_df.head())

================================================================================
LOADING NOTEBOOK 06 SAMPLE-LEVEL ARTIFACT
================================================================================

Input CSV loaded successfully.

Rows    : 338,445
Columns : 11

Columns:
 1. Test_Index
 2. True_Label
 3. Predicted_Label
 4. Confidence
 5. Confidence_Uncertainty
 6. Renyi_Evidence
 7. Confidence_Normalized
 8. Renyi_Normalized
 9. AnomalyFlow_Score
10. Decision_State
11. Security_Severity

--------------------------------------------------------------------------------
FIRST 5 ROWS
--------------------------------------------------------------------------------

,Test_Index,True_Label,Predicted_Label,Confidence,Confidence_Uncertainty,Renyi_Evidence,Confidence_Normalized,Renyi_Normalized,AnomalyFlow_Score,Decision_State,Security_Severity
0,0,NetBIOS,NetBIOS,0.274310,0.274310,0.417463,0.386017,0.056216,0.221116,NORMAL,LOW
1,1,TFTP,TFTP,0.000000,0.000000,0.714693,0.000000,0.129823,0.064911,NORMAL,LOW
2,2,Syn,Syn,0.000000,0.000000,1.309719,0.000000,0.277177,0.138588,NORMAL,LOW
3,3,TFTP,TFTP,0.000000,0.000000,0.627796,0.000000,0.108303,0.054152,NORMAL,LOW
4,4,DrDoS_SSDP,DrDoS_UDP,0.628116,0.628116,1.375605,0.883902,0.293493,0.588697,HIGH_EVIDENCE,HIGH

In [5]:
# =============================================================================
# SECTION 2 — LOAD NOTEBOOK 06 ARTIFACT
# CELL 2 — Load Notebook 06 Mitigation Input Summary
# =============================================================================

print("=" * 80)
print("LOADING NOTEBOOK 06 MITIGATION INPUT SUMMARY")
print("=" * 80)

# ---------------------------------------------------------------------------
# Load summary JSON
# ---------------------------------------------------------------------------

with open(MITIGATION_INPUT_SUMMARY, "r") as f:
    mitigation_input_summary = json.load(f)

print("\nMitigation input summary loaded successfully.")

# ---------------------------------------------------------------------------
# Display summary structure
# ---------------------------------------------------------------------------

print("\nSummary keys:")

for key in mitigation_input_summary.keys():
    print(f"- {key}")

# ---------------------------------------------------------------------------
# Display complete summary
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("NOTEBOOK 06 MITIGATION INPUT SUMMARY")
print("-" * 80)

print(json.dumps(mitigation_input_summary, indent=4))

================================================================================
LOADING NOTEBOOK 06 MITIGATION INPUT SUMMARY
================================================================================

Mitigation input summary loaded successfully.

Summary keys:
- total_test_samples
- decision_state_counts
- security_severity_counts
- baseline_accuracy
- anomalyflow_score_statistics
- sample_level_output_file

--------------------------------------------------------------------------------
NOTEBOOK 06 MITIGATION INPUT SUMMARY
--------------------------------------------------------------------------------
{
    "total_test_samples": 338445,
    "decision_state_counts": {
        "NORMAL": 270361,
        "SUSPICIOUS": 37300,
        "HIGH_EVIDENCE": 30784
    },
    "security_severity_counts": {
        "LOW": 261669,
        "MEDIUM": 36607,
        "HIGH": 30736,
        "NORMAL": 8692,
        "MONITOR": 693,
        "INVESTIGATE": 48
    },
    "baseline_accuracy": 0.8943196087990664,
    "anomalyflow_score_statistics": {
        "mean": 0.1469104951766718,
        "median": 0.08170581170153578,
        "minimum": 0.0068550517828396,
        "maximum": 0.6456887175997341
    },
    "sample_level_output_file": "/content/drive/MyDrive/Major_Project/mitigation/anomalyflow_test_results.csv"
}

# Section 3

In [6]:
# =============================================================================
# SECTION 3 — VERIFY MITIGATION INPUTS
# CELL 1 — Verify Row Count, Columns, and Test Index Integrity
# =============================================================================

print("=" * 80)
print("VERIFYING NOTEBOOK 06 MITIGATION INPUT")
print("=" * 80)

# ---------------------------------------------------------------------------
# Expected values from the verified Notebook 06 artifact
# ---------------------------------------------------------------------------

EXPECTED_ROWS = 338_445

EXPECTED_COLUMNS = [
    "Test_Index",
    "True_Label",
    "Predicted_Label",
    "Confidence",
    "Confidence_Uncertainty",
    "Renyi_Evidence",
    "Confidence_Normalized",
    "Renyi_Normalized",
    "AnomalyFlow_Score",
    "Decision_State",
    "Security_Severity",
]

# ---------------------------------------------------------------------------
# 1. Row count
# ---------------------------------------------------------------------------

actual_rows = len(mitigation_df)

row_count_pass = actual_rows == EXPECTED_ROWS

print("\n1. Row Count")
print("-" * 80)
print(f"Expected : {EXPECTED_ROWS:,}")
print(f"Actual   : {actual_rows:,}")
print(f"PASS     : {row_count_pass}")

# ---------------------------------------------------------------------------
# 2. Required columns
# ---------------------------------------------------------------------------

actual_columns = list(mitigation_df.columns)

missing_columns = [
    column for column in EXPECTED_COLUMNS
    if column not in actual_columns
]

unexpected_columns = [
    column for column in actual_columns
    if column not in EXPECTED_COLUMNS
]

columns_pass = (
    len(missing_columns) == 0
    and len(unexpected_columns) == 0
)

print("\n2. Required Columns")
print("-" * 80)
print(f"Expected columns : {len(EXPECTED_COLUMNS)}")
print(f"Actual columns   : {len(actual_columns)}")
print(f"Missing columns  : {missing_columns}")
print(f"Unexpected cols  : {unexpected_columns}")
print(f"PASS             : {columns_pass}")

# ---------------------------------------------------------------------------
# 3. Test_Index integrity
# ---------------------------------------------------------------------------

expected_indices = np.arange(EXPECTED_ROWS)

actual_indices = mitigation_df["Test_Index"].to_numpy()

index_pass = (
    len(actual_indices) == EXPECTED_ROWS
    and np.array_equal(actual_indices, expected_indices)
)

print("\n3. Test_Index Integrity")
print("-" * 80)
print(f"Expected range : 0 – {EXPECTED_ROWS - 1}")
print(f"Actual first   : {actual_indices[0]}")
print(f"Actual last    : {actual_indices[-1]}")
print(f"Unique values  : {mitigation_df['Test_Index'].nunique():,}")
print(f"PASS           : {index_pass}")

# ---------------------------------------------------------------------------
# Overall result
# ---------------------------------------------------------------------------

all_checks_pass = (
    row_count_pass
    and columns_pass
    and index_pass
)

print("\n" + "=" * 80)
print(f"INPUT STRUCTURE VERIFICATION : {all_checks_pass}")
print("=" * 80)

if not all_checks_pass:
    raise ValueError(
        "Notebook 06 mitigation input failed structural verification."
    )

================================================================================
VERIFYING NOTEBOOK 06 MITIGATION INPUT
================================================================================

1. Row Count
--------------------------------------------------------------------------------
Expected : 338,445
Actual   : 338,445
PASS     : True

2. Required Columns
--------------------------------------------------------------------------------
Expected columns : 11
Actual columns   : 11
Missing columns  : []
Unexpected cols  : []
PASS             : True

3. Test_Index Integrity
--------------------------------------------------------------------------------
Expected range : 0 – 338444
Actual first   : 0
Actual last    : 338444
Unique values  : 338,445
PASS           : True

================================================================================
INPUT STRUCTURE VERIFICATION : True
================================================================================

In [7]:
# =============================================================================
# SECTION 3 — VERIFY MITIGATION INPUTS
# CELL 2 — Verify Decision-State and Security-Severity Distributions
# =============================================================================

print("=" * 80)
print("VERIFYING NOTEBOOK 06 DECISION DISTRIBUTIONS")
print("=" * 80)

# ---------------------------------------------------------------------------
# Expected distributions from the verified Notebook 06 summary
# ---------------------------------------------------------------------------

EXPECTED_DECISION_STATES = {
    "NORMAL": 270_361,
    "SUSPICIOUS": 37_300,
    "HIGH_EVIDENCE": 30_784,
}

EXPECTED_SECURITY_SEVERITIES = {
    "LOW": 261_669,
    "MEDIUM": 36_607,
    "HIGH": 30_736,
    "NORMAL": 8_692,
    "MONITOR": 693,
    "INVESTIGATE": 48,
}

# ---------------------------------------------------------------------------
# Actual distributions
# ---------------------------------------------------------------------------

actual_decision_states = (
    mitigation_df["Decision_State"]
    .value_counts()
    .to_dict()
)

actual_security_severities = (
    mitigation_df["Security_Severity"]
    .value_counts()
    .to_dict()
)

# ---------------------------------------------------------------------------
# Decision-state verification
# ---------------------------------------------------------------------------

print("\n1. Decision-State Counts")
print("-" * 80)

decision_state_pass = True

for state, expected_count in EXPECTED_DECISION_STATES.items():
    actual_count = actual_decision_states.get(state, 0)
    passed = actual_count == expected_count

    print(
        f"{state:<15} "
        f"Expected: {expected_count:>8,} | "
        f"Actual: {actual_count:>8,} | "
        f"PASS: {passed}"
    )

    if not passed:
        decision_state_pass = False

unexpected_decision_states = set(actual_decision_states) - set(
    EXPECTED_DECISION_STATES
)

if unexpected_decision_states:
    print(
        f"\nUnexpected decision states: "
        f"{sorted(unexpected_decision_states)}"
    )
    decision_state_pass = False

# ---------------------------------------------------------------------------
# Security-severity verification
# ---------------------------------------------------------------------------

print("\n2. Security-Severity Counts")
print("-" * 80)

security_severity_pass = True

for severity, expected_count in EXPECTED_SECURITY_SEVERITIES.items():
    actual_count = actual_security_severities.get(severity, 0)
    passed = actual_count == expected_count

    print(
        f"{severity:<15} "
        f"Expected: {expected_count:>8,} | "
        f"Actual: {actual_count:>8,} | "
        f"PASS: {passed}"
    )

    if not passed:
        security_severity_pass = False

unexpected_security_severities = set(actual_security_severities) - set(
    EXPECTED_SECURITY_SEVERITIES
)

if unexpected_security_severities:
    print(
        f"\nUnexpected security severities: "
        f"{sorted(unexpected_security_severities)}"
    )
    security_severity_pass = False

# ---------------------------------------------------------------------------
# Overall verification
# ---------------------------------------------------------------------------

distribution_verification_pass = (
    decision_state_pass
    and security_severity_pass
)

print("\n" + "=" * 80)
print(
    f"DECISION DISTRIBUTION VERIFICATION : "
    f"{decision_state_pass}"
)
print(
    f"SEVERITY DISTRIBUTION VERIFICATION : "
    f"{security_severity_pass}"
)
print("-" * 80)
print(
    f"OVERALL DISTRIBUTION VERIFICATION  : "
    f"{distribution_verification_pass}"
)
print("=" * 80)

if not distribution_verification_pass:
    raise ValueError(
        "Notebook 06 decision/severity distributions do not match "
        "the verified mitigation summary."
    )

================================================================================
VERIFYING NOTEBOOK 06 DECISION DISTRIBUTIONS
================================================================================

1. Decision-State Counts
--------------------------------------------------------------------------------
NORMAL          Expected:  270,361 | Actual:  270,361 | PASS: True
SUSPICIOUS      Expected:   37,300 | Actual:   37,300 | PASS: True
HIGH_EVIDENCE   Expected:   30,784 | Actual:   30,784 | PASS: True

2. Security-Severity Counts
--------------------------------------------------------------------------------
LOW             Expected:  261,669 | Actual:  261,669 | PASS: True
MEDIUM          Expected:   36,607 | Actual:   36,607 | PASS: True
HIGH            Expected:   30,736 | Actual:   30,736 | PASS: True
NORMAL          Expected:    8,692 | Actual:    8,692 | PASS: True
MONITOR         Expected:      693 | Actual:      693 | PASS: True
INVESTIGATE     Expected:       48 | Actual:       48 | PASS: True

================================================================================
DECISION DISTRIBUTION VERIFICATION : True
SEVERITY DISTRIBUTION VERIFICATION : True
--------------------------------------------------------------------------------
OVERALL DISTRIBUTION VERIFICATION  : True
================================================================================

# Section 4

In [8]:
# =============================================================================
# SECTION 4 — MITIGATION DECISION ENGINE
# CELL 1 — Define Severity-Based Mitigation Policy
# =============================================================================

print("=" * 80)
print("MITIGATION DECISION ENGINE")
print("=" * 80)

# ---------------------------------------------------------------------------
# Simulation-only mitigation policy
# ---------------------------------------------------------------------------
#
# The mitigation engine does NOT perform real network actions.
# It only assigns the mitigation action that would be recommended
# for each security severity.
#
# Severity meaning inherited from Notebook 06:
#
# NORMAL       -> No security action required
# MONITOR      -> Monitor traffic / retain for observation
# INVESTIGATE  -> Security investigation required
# LOW          -> Low-priority DDoS mitigation
# MEDIUM       -> Rate limiting
# HIGH         -> IP blocking + rate limiting
#
# ---------------------------------------------------------------------------

MITIGATION_POLICY = {
    "NORMAL": {
        "action": "NO_ACTION",
        "priority": "NONE",
        "simulation": "No mitigation required",
    },

    "MONITOR": {
        "action": "MONITOR",
        "priority": "LOW",
        "simulation": "Traffic monitored for continued suspicious activity",
    },

    "INVESTIGATE": {
        "action": "INVESTIGATE",
        "priority": "HIGH",
        "simulation": "Security investigation triggered",
    },

    "LOW": {
        "action": "ALERT",
        "priority": "LOW",
        "simulation": "Low-priority DDoS alert generated",
    },

    "MEDIUM": {
        "action": "RATE_LIMIT",
        "priority": "MEDIUM",
        "simulation": "Rate limiting simulated",
    },

    "HIGH": {
        "action": "BLOCK_AND_RATE_LIMIT",
        "priority": "CRITICAL",
        "simulation": "IP blocking and rate limiting simulated",
    },
}

# ---------------------------------------------------------------------------
# Policy verification
# ---------------------------------------------------------------------------

expected_severities = set(EXPECTED_SECURITY_SEVERITIES.keys())
policy_severities = set(MITIGATION_POLICY.keys())

policy_complete = expected_severities == policy_severities

print("\nConfigured mitigation policies:")

for severity, policy in MITIGATION_POLICY.items():
    print(
        f"\n{severity}"
        f"\n  Action     : {policy['action']}"
        f"\n  Priority   : {policy['priority']}"
        f"\n  Simulation : {policy['simulation']}"
    )

print("\n" + "-" * 80)
print(f"Policy covers all Notebook 06 severities : {policy_complete}")
print("-" * 80)

if not policy_complete:
    raise ValueError(
        "Mitigation policy does not cover every security severity "
        "produced by Notebook 06."
    )

================================================================================
MITIGATION DECISION ENGINE
================================================================================

Configured mitigation policies:

NORMAL
  Action     : NO_ACTION
  Priority   : NONE
  Simulation : No mitigation required

MONITOR
  Action     : MONITOR
  Priority   : LOW
  Simulation : Traffic monitored for continued suspicious activity

INVESTIGATE
  Action     : INVESTIGATE
  Priority   : HIGH
  Simulation : Security investigation triggered

LOW
  Action     : ALERT
  Priority   : LOW
  Simulation : Low-priority DDoS alert generated

MEDIUM
  Action     : RATE_LIMIT
  Priority   : MEDIUM
  Simulation : Rate limiting simulated

HIGH
  Action     : BLOCK_AND_RATE_LIMIT
  Priority   : CRITICAL
  Simulation : IP blocking and rate limiting simulated

--------------------------------------------------------------------------------
Policy covers all Notebook 06 severities : True
--------------------------------------------------------------------------------

In [9]:
# =============================================================================
# SECTION 4 — MITIGATION DECISION ENGINE
# CELL 2 — Finalize Severity-Based Mitigation Policy
# =============================================================================

print("=" * 80)
print("FINALIZING SEVERITY-BASED MITIGATION POLICY")
print("=" * 80)

# ---------------------------------------------------------------------------
# Final mitigation policy
# ---------------------------------------------------------------------------
#
# IMPORTANT:
# The mitigation engine is simulation-based.
#
# It determines what action SHOULD be taken for each sample but does not
# execute real firewall, router, IP-blocking, or rate-limiting commands.
#
# LOW:
#   Predicted DDoS + NORMAL AnomalyFlow evidence.
#   Traffic is NOT considered safe.
#   We alert and log rather than automatically block.
#
# MEDIUM:
#   Predicted DDoS + SUSPICIOUS evidence.
#   Rate limiting is simulated.
#
# HIGH:
#   Predicted DDoS + HIGH_EVIDENCE.
#   Blocking and rate limiting are simulated.
# ---------------------------------------------------------------------------

MITIGATION_POLICY = {
    "NORMAL": {
        "action": "NO_ACTION",
        "priority": "NONE",
        "simulation": "No mitigation required",
    },

    "MONITOR": {
        "action": "MONITOR",
        "priority": "LOW",
        "simulation": "Traffic monitored for continued suspicious activity",
    },

    "INVESTIGATE": {
        "action": "INVESTIGATE",
        "priority": "HIGH",
        "simulation": "Security investigation triggered",
    },

    "LOW": {
        "action": "ALERT_AND_LOG",
        "priority": "LOW",
        "simulation": "DDoS alert generated and traffic event logged",
    },

    "MEDIUM": {
        "action": "RATE_LIMIT",
        "priority": "MEDIUM",
        "simulation": "Traffic rate limiting simulated",
    },

    "HIGH": {
        "action": "BLOCK_AND_RATE_LIMIT",
        "priority": "CRITICAL",
        "simulation": "Traffic blocking and rate limiting simulated",
    },
}

# ---------------------------------------------------------------------------
# Verify policy completeness
# ---------------------------------------------------------------------------

expected_severities = set(EXPECTED_SECURITY_SEVERITIES.keys())
policy_severities = set(MITIGATION_POLICY.keys())

policy_complete = expected_severities == policy_severities

print("\nFinal mitigation policy:")

for severity, policy in MITIGATION_POLICY.items():
    print(
        f"\n{severity}"
        f"\n  Action     : {policy['action']}"
        f"\n  Priority   : {policy['priority']}"
        f"\n  Simulation : {policy['simulation']}"
    )

print("\n" + "-" * 80)
print(f"Policy covers all Notebook 06 severities : {policy_complete}")
print("-" * 80)

if not policy_complete:
    raise ValueError(
        "Final mitigation policy does not cover every "
        "Notebook 06 security severity."
    )

================================================================================
FINALIZING SEVERITY-BASED MITIGATION POLICY
================================================================================

Final mitigation policy:

NORMAL
  Action     : NO_ACTION
  Priority   : NONE
  Simulation : No mitigation required

MONITOR
  Action     : MONITOR
  Priority   : LOW
  Simulation : Traffic monitored for continued suspicious activity

INVESTIGATE
  Action     : INVESTIGATE
  Priority   : HIGH
  Simulation : Security investigation triggered

LOW
  Action     : ALERT_AND_LOG
  Priority   : LOW
  Simulation : DDoS alert generated and traffic event logged

MEDIUM
  Action     : RATE_LIMIT
  Priority   : MEDIUM
  Simulation : Traffic rate limiting simulated

HIGH
  Action     : BLOCK_AND_RATE_LIMIT
  Priority   : CRITICAL
  Simulation : Traffic blocking and rate limiting simulated

--------------------------------------------------------------------------------
Policy covers all Notebook 06 severities : True
--------------------------------------------------------------------------------

In [10]:
# =============================================================================
# SECTION 4 — MITIGATION DECISION ENGINE
# CELL 3 — Apply Final Mitigation Policy
# =============================================================================

print("=" * 80)
print("APPLYING FINAL MITIGATION POLICY")
print("=" * 80)

# ---------------------------------------------------------------------------
# Map security severity → mitigation action
# ---------------------------------------------------------------------------

severity_to_action = {
    severity: policy["action"]
    for severity, policy in MITIGATION_POLICY.items()
}

severity_to_priority = {
    severity: policy["priority"]
    for severity, policy in MITIGATION_POLICY.items()
}

severity_to_simulation = {
    severity: policy["simulation"]
    for severity, policy in MITIGATION_POLICY.items()
}

# ---------------------------------------------------------------------------
# Apply mappings
# ---------------------------------------------------------------------------

mitigation_df["Mitigation_Action"] = (
    mitigation_df["Security_Severity"]
    .map(severity_to_action)
)

mitigation_df["Mitigation_Priority"] = (
    mitigation_df["Security_Severity"]
    .map(severity_to_priority)
)

mitigation_df["Mitigation_Simulation"] = (
    mitigation_df["Security_Severity"]
    .map(severity_to_simulation)
)

# ---------------------------------------------------------------------------
# Verify complete mapping
# ---------------------------------------------------------------------------

missing_actions = mitigation_df["Mitigation_Action"].isna().sum()
missing_priorities = mitigation_df["Mitigation_Priority"].isna().sum()
missing_simulations = mitigation_df["Mitigation_Simulation"].isna().sum()

mapping_pass = (
    missing_actions == 0
    and missing_priorities == 0
    and missing_simulations == 0
)

print("\nMapping verification:")
print(f"Missing mitigation actions      : {missing_actions}")
print(f"Missing mitigation priorities   : {missing_priorities}")
print(f"Missing simulation descriptions : {missing_simulations}")
print(f"PASS                             : {mapping_pass}")

# ---------------------------------------------------------------------------
# Mitigation action distribution
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("MITIGATION ACTION DISTRIBUTION")
print("-" * 80)

action_counts = (
    mitigation_df["Mitigation_Action"]
    .value_counts()
)

for action, count in action_counts.items():
    percentage = (count / len(mitigation_df)) * 100

    print(
        f"{action:<24}"
        f"{count:>10,} "
        f"({percentage:>6.2f}%)"
    )

# ---------------------------------------------------------------------------
# Cross-check: severity → action
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("SEVERITY → MITIGATION ACTION")
print("-" * 80)

severity_action_table = (
    mitigation_df[
        ["Security_Severity", "Mitigation_Action"]
    ]
    .drop_duplicates()
    .sort_values("Security_Severity")
)

display(severity_action_table)

# ---------------------------------------------------------------------------
# Preview final mitigation decisions
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("SAMPLE MITIGATION DECISIONS")
print("-" * 80)

display(
    mitigation_df[
        [
            "Test_Index",
            "Predicted_Label",
            "AnomalyFlow_Score",
            "Decision_State",
            "Security_Severity",
            "Mitigation_Action",
            "Mitigation_Priority",
        ]
    ].head(10)
)

# ---------------------------------------------------------------------------
# Final validation
# ---------------------------------------------------------------------------

if not mapping_pass:
    raise ValueError(
        "One or more samples could not be assigned "
        "a mitigation decision."
    )

print("\n" + "=" * 80)
print("MITIGATION POLICY APPLICATION : PASS")
print("=" * 80)

================================================================================
APPLYING FINAL MITIGATION POLICY
================================================================================

Mapping verification:
Missing mitigation actions      : 0
Missing mitigation priorities   : 0
Missing simulation descriptions : 0
PASS                             : True

--------------------------------------------------------------------------------
MITIGATION ACTION DISTRIBUTION
--------------------------------------------------------------------------------
ALERT_AND_LOG              261,669 ( 77.32%)
RATE_LIMIT                  36,607 ( 10.82%)
BLOCK_AND_RATE_LIMIT        30,736 (  9.08%)
NO_ACTION                    8,692 (  2.57%)
MONITOR                        693 (  0.20%)
INVESTIGATE                     48 (  0.01%)

--------------------------------------------------------------------------------
SEVERITY → MITIGATION ACTION
--------------------------------------------------------------------------------

     Security_Severity     Mitigation_Action
4                 HIGH  BLOCK_AND_RATE_LIMIT
5035       INVESTIGATE           INVESTIGATE
0                  LOW         ALERT_AND_LOG
6               MEDIUM            RATE_LIMIT
150            MONITOR               MONITOR
8               NORMAL             NO_ACTION

--------------------------------------------------------------------------------
SAMPLE MITIGATION DECISIONS
--------------------------------------------------------------------------------

,Test_Index,Predicted_Label,AnomalyFlow_Score,Decision_State,Security_Severity,Mitigation_Action,Mitigation_Priority
0,0,NetBIOS,0.221116,NORMAL,LOW,ALERT_AND_LOG,LOW
1,1,TFTP,0.064911,NORMAL,LOW,ALERT_AND_LOG,LOW
2,2,Syn,0.138588,NORMAL,LOW,ALERT_AND_LOG,LOW
3,3,TFTP,0.054152,NORMAL,LOW,ALERT_AND_LOG,LOW
4,4,DrDoS_UDP,0.588697,HIGH_EVIDENCE,HIGH,BLOCK_AND_RATE_LIMIT,CRITICAL
5,5,TFTP,0.046976,NORMAL,LOW,ALERT_AND_LOG,LOW
6,6,MSSQL,0.336913,SUSPICIOUS,MEDIUM,RATE_LIMIT,MEDIUM
7,7,DrDoS_SNMP,0.034867,NORMAL,LOW,ALERT_AND_LOG,LOW
8,8,LDAP,0.056822,NORMAL,NORMAL,NO_ACTION,NONE
9,9,TFTP,0.052328,NORMAL,LOW,ALERT_AND_LOG,LOW

================================================================================
MITIGATION POLICY APPLICATION : PASS
================================================================================

# Section 5

In [11]:
# =============================================================================
# SECTION 5 — ALERT GENERATION
# CELL 1 — Define Alert Policy
# =============================================================================

print("=" * 80)
print("ALERT GENERATION")
print("=" * 80)

# ---------------------------------------------------------------------------
# Alert policy
# ---------------------------------------------------------------------------
#
# Alerts are generated from the final mitigation decision.
#
# NO_ACTION:
#   No security alert.
#
# MONITOR:
#   Monitoring alert.
#
# INVESTIGATE:
#   Investigation alert.
#
# ALERT_AND_LOG:
#   DDoS detection alert.
#
# RATE_LIMIT:
#   Rate-limit mitigation alert.
#
# BLOCK_AND_RATE_LIMIT:
#   Critical blocking alert.
# ---------------------------------------------------------------------------

ALERT_POLICY = {
    "NO_ACTION": {
        "alert_generated": False,
        "alert_level": "NONE",
        "alert_type": "NONE",
        "message": "No security action required.",
    },

    "MONITOR": {
        "alert_generated": True,
        "alert_level": "LOW",
        "alert_type": "MONITORING",
        "message": "Suspicious traffic requires continued monitoring.",
    },

    "INVESTIGATE": {
        "alert_generated": True,
        "alert_level": "HIGH",
        "alert_type": "INVESTIGATION",
        "message": "Non-DDoS traffic shows high security evidence and requires investigation.",
    },

    "ALERT_AND_LOG": {
        "alert_generated": True,
        "alert_level": "LOW",
        "alert_type": "DDOS_DETECTED",
        "message": "DDoS traffic detected with low AnomalyFlow evidence; event logged.",
    },

    "RATE_LIMIT": {
        "alert_generated": True,
        "alert_level": "MEDIUM",
        "alert_type": "RATE_LIMIT_TRIGGERED",
        "message": "DDoS traffic detected with suspicious evidence; rate limiting simulated.",
    },

    "BLOCK_AND_RATE_LIMIT": {
        "alert_generated": True,
        "alert_level": "CRITICAL",
        "alert_type": "BLOCK_TRIGGERED",
        "message": "High-evidence DDoS traffic detected; blocking and rate limiting simulated.",
    },
}

# ---------------------------------------------------------------------------
# Verify alert policy completeness
# ---------------------------------------------------------------------------

expected_actions = set(MITIGATION_POLICY.keys())

# The policy keys are severities, so obtain all actual mitigation actions.
expected_actions = set(MITIGATION_POLICY[s]["action"] for s in MITIGATION_POLICY)

alert_policy_actions = set(ALERT_POLICY.keys())

alert_policy_complete = expected_actions == alert_policy_actions

print("\nConfigured alert policies:")

for action, policy in ALERT_POLICY.items():
    print(
        f"\n{action}"
        f"\n  Alert Generated : {policy['alert_generated']}"
        f"\n  Alert Level     : {policy['alert_level']}"
        f"\n  Alert Type      : {policy['alert_type']}"
        f"\n  Message         : {policy['message']}"
    )

print("\n" + "-" * 80)
print(f"Alert policy covers all mitigation actions : {alert_policy_complete}")
print("-" * 80)

if not alert_policy_complete:
    raise ValueError(
        "Alert policy does not cover every mitigation action."
    )

================================================================================
ALERT GENERATION
================================================================================

Configured alert policies:

NO_ACTION
  Alert Generated : False
  Alert Level     : NONE
  Alert Type      : NONE
  Message         : No security action required.

MONITOR
  Alert Generated : True
  Alert Level     : LOW
  Alert Type      : MONITORING
  Message         : Suspicious traffic requires continued monitoring.

INVESTIGATE
  Alert Generated : True
  Alert Level     : HIGH
  Alert Type      : INVESTIGATION
  Message         : Non-DDoS traffic shows high security evidence and requires investigation.

ALERT_AND_LOG
  Alert Generated : True
  Alert Level     : LOW
  Alert Type      : DDOS_DETECTED
  Message         : DDoS traffic detected with low AnomalyFlow evidence; event logged.

RATE_LIMIT
  Alert Generated : True
  Alert Level     : MEDIUM
  Alert Type      : RATE_LIMIT_TRIGGERED
  Message         : DDoS traffic detected with suspicious evidence; rate limiting simulated.

BLOCK_AND_RATE_LIMIT
  Alert Generated : True
  Alert Level     : CRITICAL
  Alert Type      : BLOCK_TRIGGERED
  Message         : High-evidence DDoS traffic detected; blocking and rate limiting simulated.

--------------------------------------------------------------------------------
Alert policy covers all mitigation actions : True
--------------------------------------------------------------------------------

In [12]:
# =============================================================================
# SECTION 5 — ALERT GENERATION
# CELL 2 — Generate Sample-Level Security Alerts
# =============================================================================

print("=" * 80)
print("GENERATING SAMPLE-LEVEL SECURITY ALERTS")
print("=" * 80)

# ---------------------------------------------------------------------------
# Create lookup dictionaries
# ---------------------------------------------------------------------------

action_to_alert_generated = {
    action: policy["alert_generated"]
    for action, policy in ALERT_POLICY.items()
}

action_to_alert_level = {
    action: policy["alert_level"]
    for action, policy in ALERT_POLICY.items()
}

action_to_alert_type = {
    action: policy["alert_type"]
    for action, policy in ALERT_POLICY.items()
}

action_to_alert_message = {
    action: policy["message"]
    for action, policy in ALERT_POLICY.items()
}

# ---------------------------------------------------------------------------
# Apply alert policy
# ---------------------------------------------------------------------------

mitigation_df["Alert_Generated"] = (
    mitigation_df["Mitigation_Action"]
    .map(action_to_alert_generated)
)

mitigation_df["Alert_Level"] = (
    mitigation_df["Mitigation_Action"]
    .map(action_to_alert_level)
)

mitigation_df["Alert_Type"] = (
    mitigation_df["Mitigation_Action"]
    .map(action_to_alert_type)
)

mitigation_df["Alert_Message"] = (
    mitigation_df["Mitigation_Action"]
    .map(action_to_alert_message)
)

# ---------------------------------------------------------------------------
# Verify complete alert mapping
# ---------------------------------------------------------------------------

missing_alert_flags = mitigation_df["Alert_Generated"].isna().sum()
missing_alert_levels = mitigation_df["Alert_Level"].isna().sum()
missing_alert_types = mitigation_df["Alert_Type"].isna().sum()
missing_alert_messages = mitigation_df["Alert_Message"].isna().sum()

alert_mapping_pass = (
    missing_alert_flags == 0
    and missing_alert_levels == 0
    and missing_alert_types == 0
    and missing_alert_messages == 0
)

print("\nAlert mapping verification:")
print(f"Missing alert flags     : {missing_alert_flags}")
print(f"Missing alert levels    : {missing_alert_levels}")
print(f"Missing alert types     : {missing_alert_types}")
print(f"Missing alert messages  : {missing_alert_messages}")
print(f"PASS                    : {alert_mapping_pass}")

# ---------------------------------------------------------------------------
# Alert generation distribution
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("ALERT GENERATION DISTRIBUTION")
print("-" * 80)

alert_counts = (
    mitigation_df["Alert_Generated"]
    .value_counts()
    .sort_index()
)

for generated, count in alert_counts.items():
    percentage = (count / len(mitigation_df)) * 100

    print(
        f"Alert Generated = {generated:<5} "
        f"{count:>10,} "
        f"({percentage:>6.2f}%)"
    )

# ---------------------------------------------------------------------------
# Alert type distribution
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("ALERT TYPE DISTRIBUTION")
print("-" * 80)

alert_type_counts = (
    mitigation_df["Alert_Type"]
    .value_counts()
)

for alert_type, count in alert_type_counts.items():
    percentage = (count / len(mitigation_df)) * 100

    print(
        f"{alert_type:<24}"
        f"{count:>10,} "
        f"({percentage:>6.2f}%)"
    )

# ---------------------------------------------------------------------------
# Alert level distribution
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("ALERT LEVEL DISTRIBUTION")
print("-" * 80)

alert_level_counts = (
    mitigation_df["Alert_Level"]
    .value_counts()
)

for level, count in alert_level_counts.items():
    percentage = (count / len(mitigation_df)) * 100

    print(
        f"{level:<12}"
        f"{count:>10,} "
        f"({percentage:>6.2f}%)"
    )

# ---------------------------------------------------------------------------
# Preview generated alerts
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("SAMPLE GENERATED ALERTS")
print("-" * 80)

display(
    mitigation_df[
        [
            "Test_Index",
            "Predicted_Label",
            "Decision_State",
            "Security_Severity",
            "Mitigation_Action",
            "Alert_Generated",
            "Alert_Level",
            "Alert_Type",
        ]
    ].head(10)
)

# ---------------------------------------------------------------------------
# Final validation
# ---------------------------------------------------------------------------

if not alert_mapping_pass:
    raise ValueError(
        "One or more samples could not be assigned "
        "a complete alert decision."
    )

print("\n" + "=" * 80)
print("SAMPLE-LEVEL ALERT GENERATION : PASS")
print("=" * 80)

================================================================================
GENERATING SAMPLE-LEVEL SECURITY ALERTS
================================================================================

Alert mapping verification:
Missing alert flags     : 0
Missing alert levels    : 0
Missing alert types     : 0
Missing alert messages  : 0
PASS                    : True

--------------------------------------------------------------------------------
ALERT GENERATION DISTRIBUTION
--------------------------------------------------------------------------------
Alert Generated = 0          8,692 (  2.57%)
Alert Generated = 1        329,753 ( 97.43%)

--------------------------------------------------------------------------------
ALERT TYPE DISTRIBUTION
--------------------------------------------------------------------------------
DDOS_DETECTED              261,669 ( 77.32%)
RATE_LIMIT_TRIGGERED        36,607 ( 10.82%)
BLOCK_TRIGGERED             30,736 (  9.08%)
NONE                         8,692 (  2.57%)
MONITORING                     693 (  0.20%)
INVESTIGATION                   48 (  0.01%)

--------------------------------------------------------------------------------
ALERT LEVEL DISTRIBUTION
--------------------------------------------------------------------------------
LOW            262,362 ( 77.52%)
MEDIUM          36,607 ( 10.82%)
CRITICAL        30,736 (  9.08%)
NONE             8,692 (  2.57%)
HIGH                48 (  0.01%)

--------------------------------------------------------------------------------
SAMPLE GENERATED ALERTS
--------------------------------------------------------------------------------

,Test_Index,Predicted_Label,Decision_State,Security_Severity,Mitigation_Action,Alert_Generated,Alert_Level,Alert_Type
0,0,NetBIOS,NORMAL,LOW,ALERT_AND_LOG,True,LOW,DDOS_DETECTED
1,1,TFTP,NORMAL,LOW,ALERT_AND_LOG,True,LOW,DDOS_DETECTED
2,2,Syn,NORMAL,LOW,ALERT_AND_LOG,True,LOW,DDOS_DETECTED
3,3,TFTP,NORMAL,LOW,ALERT_AND_LOG,True,LOW,DDOS_DETECTED
4,4,DrDoS_UDP,HIGH_EVIDENCE,HIGH,BLOCK_AND_RATE_LIMIT,True,CRITICAL,BLOCK_TRIGGERED
5,5,TFTP,NORMAL,LOW,ALERT_AND_LOG,True,LOW,DDOS_DETECTED
6,6,MSSQL,SUSPICIOUS,MEDIUM,RATE_LIMIT,True,MEDIUM,RATE_LIMIT_TRIGGERED
7,7,DrDoS_SNMP,NORMAL,LOW,ALERT_AND_LOG,True,LOW,DDOS_DETECTED
8,8,LDAP,NORMAL,NORMAL,NO_ACTION,False,NONE,NONE
9,9,TFTP,NORMAL,LOW,ALERT_AND_LOG,True,LOW,DDOS_DETECTED

================================================================================
SAMPLE-LEVEL ALERT GENERATION : PASS
================================================================================

# Section 6

In [13]:
# =============================================================================
# SECTION 6 — MITIGATION SIMULATION
# CELL 1 — Generate Mitigation Simulation Flags
# =============================================================================

print("=" * 80)
print("MITIGATION SIMULATION")
print("=" * 80)

# ---------------------------------------------------------------------------
# Simulation flags
# ---------------------------------------------------------------------------
#
# These flags represent what the mitigation engine WOULD do.
# No real network action is executed.
# ---------------------------------------------------------------------------

mitigation_df["Simulated_Block"] = (
    mitigation_df["Mitigation_Action"]
    == "BLOCK_AND_RATE_LIMIT"
)

mitigation_df["Simulated_Rate_Limit"] = (
    mitigation_df["Mitigation_Action"].isin(
        [
            "RATE_LIMIT",
            "BLOCK_AND_RATE_LIMIT",
        ]
    )
)

mitigation_df["Simulated_Monitoring"] = (
    mitigation_df["Mitigation_Action"]
    == "MONITOR"
)

mitigation_df["Simulated_Investigation"] = (
    mitigation_df["Mitigation_Action"]
    == "INVESTIGATE"
)

# ---------------------------------------------------------------------------
# Verify flag integrity
# ---------------------------------------------------------------------------

expected_block_count = (
    mitigation_df["Security_Severity"] == "HIGH"
).sum()

expected_rate_limit_count = (
    mitigation_df["Security_Severity"].isin(
        ["MEDIUM", "HIGH"]
    )
).sum()

expected_monitor_count = (
    mitigation_df["Security_Severity"] == "MONITOR"
).sum()

expected_investigation_count = (
    mitigation_df["Security_Severity"] == "INVESTIGATE"
).sum()

actual_block_count = mitigation_df["Simulated_Block"].sum()
actual_rate_limit_count = mitigation_df["Simulated_Rate_Limit"].sum()
actual_monitor_count = mitigation_df["Simulated_Monitoring"].sum()
actual_investigation_count = mitigation_df["Simulated_Investigation"].sum()

simulation_pass = (
    actual_block_count == expected_block_count
    and actual_rate_limit_count == expected_rate_limit_count
    and actual_monitor_count == expected_monitor_count
    and actual_investigation_count == expected_investigation_count
)

print("\nSimulation counts:")
print(
    f"Simulated blocking       : "
    f"{actual_block_count:,}"
)

print(
    f"Simulated rate limiting : "
    f"{actual_rate_limit_count:,}"
)

print(
    f"Simulated monitoring    : "
    f"{actual_monitor_count:,}"
)

print(
    f"Simulated investigation : "
    f"{actual_investigation_count:,}"
)

print("\n" + "-" * 80)
print(f"MITIGATION FLAG VERIFICATION : {simulation_pass}")
print("-" * 80)

if not simulation_pass:
    raise ValueError(
        "Mitigation simulation flags do not match "
        "the defined mitigation policy."
    )

# ---------------------------------------------------------------------------
# Display action matrix
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("MITIGATION ACTION MATRIX")
print("-" * 80)

action_matrix = (
    mitigation_df[
        [
            "Security_Severity",
            "Mitigation_Action",
            "Simulated_Block",
            "Simulated_Rate_Limit",
            "Simulated_Monitoring",
            "Simulated_Investigation",
        ]
    ]
    .drop_duplicates()
    .sort_values("Security_Severity")
)

display(action_matrix)

print("\n" + "=" * 80)
print("MITIGATION SIMULATION FLAGS : PASS")
print("=" * 80)

================================================================================
MITIGATION SIMULATION
================================================================================

Simulation counts:
Simulated blocking       : 30,736
Simulated rate limiting : 67,343
Simulated monitoring    : 693
Simulated investigation : 48

--------------------------------------------------------------------------------
MITIGATION FLAG VERIFICATION : True
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
MITIGATION ACTION MATRIX
--------------------------------------------------------------------------------

,Security_Severity,Mitigation_Action,Simulated_Block,Simulated_Rate_Limit,Simulated_Monitoring,Simulated_Investigation
4,HIGH,BLOCK_AND_RATE_LIMIT,True,True,False,False
5035,INVESTIGATE,INVESTIGATE,False,False,False,True
0,LOW,ALERT_AND_LOG,False,False,False,False
6,MEDIUM,RATE_LIMIT,False,True,False,False
150,MONITOR,MONITOR,False,False,True,False
8,NORMAL,NO_ACTION,False,False,False,False

================================================================================
MITIGATION SIMULATION FLAGS : PASS
================================================================================

In [14]:
# =============================================================================
# SECTION 6 — MITIGATION SIMULATION
# CELL 2 — Generate Mitigation Outcome
# =============================================================================

print("=" * 80)
print("GENERATING MITIGATION OUTCOMES")
print("=" * 80)

# ---------------------------------------------------------------------------
# Define mitigation outcome for each action
# ---------------------------------------------------------------------------

MITIGATION_OUTCOME = {
    "NO_ACTION": "NO_ACTION_REQUIRED",
    "MONITOR": "MONITORING_ACTIVE",
    "INVESTIGATE": "INVESTIGATION_REQUIRED",
    "ALERT_AND_LOG": "ALERT_LOGGED",
    "RATE_LIMIT": "RATE_LIMIT_SIMULATED",
    "BLOCK_AND_RATE_LIMIT": "BLOCK_AND_RATE_LIMIT_SIMULATED",
}

# ---------------------------------------------------------------------------
# Apply mitigation outcomes
# ---------------------------------------------------------------------------

mitigation_df["Mitigation_Outcome"] = (
    mitigation_df["Mitigation_Action"]
    .map(MITIGATION_OUTCOME)
)

# ---------------------------------------------------------------------------
# Verify complete mapping
# ---------------------------------------------------------------------------

missing_outcomes = (
    mitigation_df["Mitigation_Outcome"]
    .isna()
    .sum()
)

outcome_pass = missing_outcomes == 0

print("\nOutcome mapping verification:")
print(f"Missing mitigation outcomes : {missing_outcomes}")
print(f"PASS                         : {outcome_pass}")

# ---------------------------------------------------------------------------
# Outcome distribution
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("MITIGATION OUTCOME DISTRIBUTION")
print("-" * 80)

outcome_counts = (
    mitigation_df["Mitigation_Outcome"]
    .value_counts()
)

for outcome, count in outcome_counts.items():
    percentage = (count / len(mitigation_df)) * 100

    print(
        f"{outcome:<32}"
        f"{count:>10,} "
        f"({percentage:>6.2f}%)"
    )

# ---------------------------------------------------------------------------
# Preview mitigation outcomes
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("SAMPLE MITIGATION OUTCOMES")
print("-" * 80)

display(
    mitigation_df[
        [
            "Test_Index",
            "Decision_State",
            "Security_Severity",
            "Mitigation_Action",
            "Alert_Type",
            "Simulated_Block",
            "Simulated_Rate_Limit",
            "Mitigation_Outcome",
        ]
    ].head(10)
)

# ---------------------------------------------------------------------------
# Final validation
# ---------------------------------------------------------------------------

if not outcome_pass:
    raise ValueError(
        "One or more mitigation actions could not be assigned "
        "a mitigation outcome."
    )

print("\n" + "=" * 80)
print("MITIGATION OUTCOME GENERATION : PASS")
print("=" * 80)

================================================================================
GENERATING MITIGATION OUTCOMES
================================================================================

Outcome mapping verification:
Missing mitigation outcomes : 0
PASS                         : True

--------------------------------------------------------------------------------
MITIGATION OUTCOME DISTRIBUTION
--------------------------------------------------------------------------------
ALERT_LOGGED                       261,669 ( 77.32%)
RATE_LIMIT_SIMULATED                36,607 ( 10.82%)
BLOCK_AND_RATE_LIMIT_SIMULATED      30,736 (  9.08%)
NO_ACTION_REQUIRED                   8,692 (  2.57%)
MONITORING_ACTIVE                      693 (  0.20%)
INVESTIGATION_REQUIRED                  48 (  0.01%)

--------------------------------------------------------------------------------
SAMPLE MITIGATION OUTCOMES
--------------------------------------------------------------------------------

,Test_Index,Decision_State,Security_Severity,Mitigation_Action,Alert_Type,Simulated_Block,Simulated_Rate_Limit,Mitigation_Outcome
0,0,NORMAL,LOW,ALERT_AND_LOG,DDOS_DETECTED,False,False,ALERT_LOGGED
1,1,NORMAL,LOW,ALERT_AND_LOG,DDOS_DETECTED,False,False,ALERT_LOGGED
2,2,NORMAL,LOW,ALERT_AND_LOG,DDOS_DETECTED,False,False,ALERT_LOGGED
3,3,NORMAL,LOW,ALERT_AND_LOG,DDOS_DETECTED,False,False,ALERT_LOGGED
4,4,HIGH_EVIDENCE,HIGH,BLOCK_AND_RATE_LIMIT,BLOCK_TRIGGERED,True,True,BLOCK_AND_RATE_LIMIT_SIMULATED
5,5,NORMAL,LOW,ALERT_AND_LOG,DDOS_DETECTED,False,False,ALERT_LOGGED
6,6,SUSPICIOUS,MEDIUM,RATE_LIMIT,RATE_LIMIT_TRIGGERED,False,True,RATE_LIMIT_SIMULATED
7,7,NORMAL,LOW,ALERT_AND_LOG,DDOS_DETECTED,False,False,ALERT_LOGGED
8,8,NORMAL,NORMAL,NO_ACTION,NONE,False,False,NO_ACTION_REQUIRED
9,9,NORMAL,LOW,ALERT_AND_LOG,DDOS_DETECTED,False,False,ALERT_LOGGED

================================================================================
MITIGATION OUTCOME GENERATION : PASS
================================================================================

In [15]:
# =============================================================================
# SECTION 6 — MITIGATION SIMULATION
# CELL 3 — Generate Mitigation Summary Statistics
# =============================================================================

print("=" * 80)
print("MITIGATION SIMULATION SUMMARY")
print("=" * 80)

# ---------------------------------------------------------------------------
# Total samples
# ---------------------------------------------------------------------------

total_samples = len(mitigation_df)

# ---------------------------------------------------------------------------
# Mitigation action counts
# ---------------------------------------------------------------------------

mitigation_action_counts = (
    mitigation_df["Mitigation_Action"]
    .value_counts()
    .to_dict()
)

# ---------------------------------------------------------------------------
# Alert counts
# ---------------------------------------------------------------------------

total_alerts = int(
    mitigation_df["Alert_Generated"].sum()
)

total_no_alert = int(
    (~mitigation_df["Alert_Generated"]).sum()
)

# ---------------------------------------------------------------------------
# Simulated mitigation counts
# ---------------------------------------------------------------------------

total_blocked = int(
    mitigation_df["Simulated_Block"].sum()
)

total_rate_limited = int(
    mitigation_df["Simulated_Rate_Limit"].sum()
)

total_monitored = int(
    mitigation_df["Simulated_Monitoring"].sum()
)

total_investigated = int(
    mitigation_df["Simulated_Investigation"].sum()
)

# ---------------------------------------------------------------------------
# Percentages
# ---------------------------------------------------------------------------

def percentage(count, total):
    return round((count / total) * 100, 4)


# ---------------------------------------------------------------------------
# Display summary
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("OVERALL COUNTS")
print("-" * 80)

print(f"Total test samples       : {total_samples:,}")
print(f"Alerts generated        : {total_alerts:,}")
print(f"No alert required       : {total_no_alert:,}")
print(f"Simulated blocking      : {total_blocked:,}")
print(f"Simulated rate limiting : {total_rate_limited:,}")
print(f"Simulated monitoring    : {total_monitored:,}")
print(f"Investigations required : {total_investigated:,}")

print("\n" + "-" * 80)
print("OVERALL PERCENTAGES")
print("-" * 80)

print(
    f"Alert rate              : "
    f"{percentage(total_alerts, total_samples):.2f}%"
)

print(
    f"Simulated blocking rate : "
    f"{percentage(total_blocked, total_samples):.2f}%"
)

print(
    f"Rate-limit rate         : "
    f"{percentage(total_rate_limited, total_samples):.2f}%"
)

print(
    f"Monitoring rate         : "
    f"{percentage(total_monitored, total_samples):.2f}%"
)

print(
    f"Investigation rate      : "
    f"{percentage(total_investigated, total_samples):.2f}%"
)

# ---------------------------------------------------------------------------
# Severity-wise mitigation summary
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("SEVERITY-WISE MITIGATION SUMMARY")
print("-" * 80)

severity_summary = (
    mitigation_df
    .groupby("Security_Severity")
    .agg(
        Samples=("Test_Index", "count"),
        Alerts=("Alert_Generated", "sum"),
        Blocked=("Simulated_Block", "sum"),
        Rate_Limited=("Simulated_Rate_Limit", "sum"),
        Monitored=("Simulated_Monitoring", "sum"),
        Investigated=("Simulated_Investigation", "sum"),
    )
    .reindex(EXPECTED_SECURITY_SEVERITIES.keys())
    .fillna(0)
    .astype(int)
)

severity_summary["Percentage"] = (
    severity_summary["Samples"]
    / total_samples
    * 100
).round(2)

display(severity_summary)

# ---------------------------------------------------------------------------
# Create machine-readable summary object
# ---------------------------------------------------------------------------

mitigation_simulation_summary = {
    "total_test_samples": total_samples,
    "alerts_generated": total_alerts,
    "no_alert_required": total_no_alert,
    "simulated_blocking": total_blocked,
    "simulated_rate_limiting": total_rate_limited,
    "simulated_monitoring": total_monitored,
    "investigations_required": total_investigated,
    "alert_rate_percent": percentage(total_alerts, total_samples),
    "simulated_blocking_rate_percent": percentage(
        total_blocked,
        total_samples
    ),
    "rate_limiting_rate_percent": percentage(
        total_rate_limited,
        total_samples
    ),
    "monitoring_rate_percent": percentage(
        total_monitored,
        total_samples
    ),
    "investigation_rate_percent": percentage(
        total_investigated,
        total_samples
    ),
    "mitigation_action_counts": mitigation_action_counts,
}

print("\n" + "=" * 80)
print("MITIGATION SUMMARY GENERATION : PASS")
print("=" * 80)

================================================================================
MITIGATION SIMULATION SUMMARY
================================================================================

--------------------------------------------------------------------------------
OVERALL COUNTS
--------------------------------------------------------------------------------
Total test samples       : 338,445
Alerts generated        : 329,753
No alert required       : 8,692
Simulated blocking      : 30,736
Simulated rate limiting : 67,343
Simulated monitoring    : 693
Investigations required : 48

--------------------------------------------------------------------------------
OVERALL PERCENTAGES
--------------------------------------------------------------------------------
Alert rate              : 97.43%
Simulated blocking rate : 9.08%
Rate-limit rate         : 19.90%
Monitoring rate         : 0.20%
Investigation rate      : 0.01%

--------------------------------------------------------------------------------
SEVERITY-WISE MITIGATION SUMMARY
--------------------------------------------------------------------------------

,Samples,Alerts,Blocked,Rate_Limited,Monitored,Investigated,Percentage
Security_Severity,,,,,,,
LOW,261669,261669,0,0,0,0,77.32
MEDIUM,36607,36607,0,36607,0,0,10.82
HIGH,30736,30736,30736,30736,0,0,9.08
NORMAL,8692,0,0,0,0,0,2.57
MONITOR,693,693,0,0,693,0,0.20
INVESTIGATE,48,48,0,0,0,48,0.01

================================================================================
MITIGATION SUMMARY GENERATION : PASS
================================================================================

# Section 7

In [17]:
# =============================================================================
# SECTION 7 — SAVE FINAL MITIGATION OUTPUTS
# CELL 1 — Prepare Final Sample-Level Mitigation Output
# =============================================================================

print("=" * 80)
print("PREPARING FINAL MITIGATION OUTPUT")
print("=" * 80)

# ---------------------------------------------------------------------------
# Final output column order
# ---------------------------------------------------------------------------

FINAL_OUTPUT_COLUMNS = [
    # Notebook 06 source fields
    "Test_Index",
    "True_Label",
    "Predicted_Label",
    "Confidence",
    "Confidence_Uncertainty",
    "Renyi_Evidence",
    "Confidence_Normalized",
    "Renyi_Normalized",
    "AnomalyFlow_Score",
    "Decision_State",
    "Security_Severity",

    # Notebook 07 mitigation fields
    "Mitigation_Action",
    "Mitigation_Priority",
    "Mitigation_Simulation",

    # Alert fields
    "Alert_Generated",
    "Alert_Level",
    "Alert_Type",
    "Alert_Message",

    # Simulation fields
    "Simulated_Block",
    "Simulated_Rate_Limit",
    "Simulated_Monitoring",
    "Simulated_Investigation",
    "Mitigation_Outcome",
]

# ---------------------------------------------------------------------------
# Verify required columns
# ---------------------------------------------------------------------------

missing_final_columns = [
    column
    for column in FINAL_OUTPUT_COLUMNS
    if column not in mitigation_df.columns
]

print("\nMissing final output columns:")
print(missing_final_columns)

if missing_final_columns:
    raise ValueError(
        f"Final mitigation output is missing columns: "
        f"{missing_final_columns}"
    )

# ---------------------------------------------------------------------------
# Create final output DataFrame
# ---------------------------------------------------------------------------

final_mitigation_df = mitigation_df[
    FINAL_OUTPUT_COLUMNS
].copy()

# ---------------------------------------------------------------------------
# Verify row count
# ---------------------------------------------------------------------------

row_count_pass = (
    len(final_mitigation_df) == 338_445
)

# ---------------------------------------------------------------------------
# Verify Test_Index integrity
# ---------------------------------------------------------------------------

test_index_pass = (
    final_mitigation_df["Test_Index"].nunique() == 338_445
    and final_mitigation_df["Test_Index"].iloc[0] == 0
    and final_mitigation_df["Test_Index"].iloc[-1] == 338_444
)

# ---------------------------------------------------------------------------
# Verify final output schema
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("FINAL OUTPUT VERIFICATION")
print("-" * 80)

print(f"Rows              : {len(final_mitigation_df):,}")
print(f"Columns           : {len(final_mitigation_df.columns)}")
print(f"Row count PASS    : {row_count_pass}")
print(f"Test_Index PASS   : {test_index_pass}")

print("\nFinal columns:")

for i, column in enumerate(final_mitigation_df.columns, start=1):
    print(f"{i:2d}. {column}")

# ---------------------------------------------------------------------------
# Preview
# ---------------------------------------------------------------------------

print("\n" + "-" * 80)
print("FINAL MITIGATION OUTPUT PREVIEW")
print("-" * 80)

display(final_mitigation_df.head(10))

# ---------------------------------------------------------------------------
# Final preparation check
# ---------------------------------------------------------------------------

output_preparation_pass = (
    len(missing_final_columns) == 0
    and row_count_pass
    and test_index_pass
)

print("\n" + "=" * 80)
print(f"FINAL OUTPUT PREPARATION : {output_preparation_pass}")
print("=" * 80)

if not output_preparation_pass:
    raise ValueError(
        "Final mitigation output preparation failed."
    )

================================================================================
PREPARING FINAL MITIGATION OUTPUT
================================================================================

Missing final output columns:
[]

--------------------------------------------------------------------------------
FINAL OUTPUT VERIFICATION
--------------------------------------------------------------------------------
Rows              : 338,445
Columns           : 23
Row count PASS    : True
Test_Index PASS   : True

Final columns:
 1. Test_Index
 2. True_Label
 3. Predicted_Label
 4. Confidence
 5. Confidence_Uncertainty
 6. Renyi_Evidence
 7. Confidence_Normalized
 8. Renyi_Normalized
 9. AnomalyFlow_Score
10. Decision_State
11. Security_Severity
12. Mitigation_Action
13. Mitigation_Priority
14. Mitigation_Simulation
15. Alert_Generated
16. Alert_Level
17. Alert_Type
18. Alert_Message
19. Simulated_Block
20. Simulated_Rate_Limit
21. Simulated_Monitoring
22. Simulated_Investigation
23. Mitigation_Outcome

--------------------------------------------------------------------------------
FINAL MITIGATION OUTPUT PREVIEW
--------------------------------------------------------------------------------

,Test_Index,True_Label,Predicted_Label,Confidence,Confidence_Uncertainty,Renyi_Evidence,Confidence_Normalized,Renyi_Normalized,AnomalyFlow_Score,Decision_State,...,Mitigation_Simulation,Alert_Generated,Alert_Level,Alert_Type,Alert_Message,Simulated_Block,Simulated_Rate_Limit,Simulated_Monitoring,Simulated_Investigation,Mitigation_Outcome
0,0,NetBIOS,NetBIOS,0.274310,0.274310,0.417463,0.386017,0.056216,0.221116,NORMAL,...,DDoS alert generated and traffic event logged,True,LOW,DDOS_DETECTED,DDoS traffic detected with low AnomalyFlow evi...,False,False,False,False,ALERT_LOGGED
1,1,TFTP,TFTP,0.000000,0.000000,0.714693,0.000000,0.129823,0.064911,NORMAL,...,DDoS alert generated and traffic event logged,True,LOW,DDOS_DETECTED,DDoS traffic detected with low AnomalyFlow evi...,False,False,False,False,ALERT_LOGGED
2,2,Syn,Syn,0.000000,0.000000,1.309719,0.000000,0.277177,0.138588,NORMAL,...,DDoS alert generated and traffic event logged,True,LOW,DDOS_DETECTED,DDoS traffic detected with low AnomalyFlow evi...,False,False,False,False,ALERT_LOGGED
3,3,TFTP,TFTP,0.000000,0.000000,0.627796,0.000000,0.108303,0.054152,NORMAL,...,DDoS alert generated and traffic event logged,True,LOW,DDOS_DETECTED,DDoS traffic detected with low AnomalyFlow evi...,False,False,False,False,ALERT_LOGGED
4,4,DrDoS_SSDP,DrDoS_UDP,0.628116,0.628116,1.375605,0.883902,0.293493,0.588697,HIGH_EVIDENCE,...,Traffic blocking and rate limiting simulated,True,CRITICAL,BLOCK_TRIGGERED,High-evidence DDoS traffic detected; blocking ...,True,True,False,False,BLOCK_AND_RATE_LIMIT_SIMULATED
5,5,TFTP,TFTP,0.000000,0.000000,0.569848,0.000000,0.093953,0.046976,NORMAL,...,DDoS alert generated and traffic event logged,True,LOW,DDOS_DETECTED,DDoS traffic detected with low AnomalyFlow evi...,False,False,False,False,ALERT_LOGGED
6,6,MSSQL,MSSQL,0.341372,0.341372,0.971577,0.480387,0.193438,0.336913,SUSPICIOUS,...,Traffic rate limiting simulated,True,MEDIUM,RATE_LIMIT_TRIGGERED,DDoS traffic detected with suspicious evidence...,False,True,False,False,RATE_LIMIT_SIMULATED
7,7,DrDoS_SNMP,DrDoS_SNMP,0.000002,0.000002,0.472041,0.000003,0.069732,0.034867,NORMAL,...,DDoS alert generated and traffic event logged,True,LOW,DDOS_DETECTED,DDoS traffic detected with low AnomalyFlow evi...,False,False,False,False,ALERT_LOGGED
8,8,LDAP,LDAP,0.009738,0.009738,0.594023,0.013703,0.099940,0.056822,NORMAL,...,No mitigation required,False,NONE,NONE,No security action required.,False,False,False,False,NO_ACTION_REQUIRED
9,9,TFTP,TFTP,0.000000,0.000000,0.613070,0.000000,0.104657,0.052328,NORMAL,...,DDoS alert generated and traffic event logged,True,LOW,DDOS_DETECTED,DDoS traffic detected with low AnomalyFlow evi...,False,False,False,False,ALERT_LOGGED

================================================================================
FINAL OUTPUT PREPARATION : True
================================================================================

In [18]:
# =============================================================================
# SECTION 7 — SAVE FINAL MITIGATION OUTPUTS
# CELL 2 — Save Final Sample-Level Mitigation CSV
# =============================================================================

print("=" * 80)
print("SAVING FINAL MITIGATION OUTPUT")
print("=" * 80)

# ---------------------------------------------------------------------------
# Output path
# ---------------------------------------------------------------------------

FINAL_MITIGATION_CSV = (
    MITIGATION_DIR / "final_mitigation_results.csv"
)

# ---------------------------------------------------------------------------
# Save sample-level mitigation results
# ---------------------------------------------------------------------------

final_mitigation_df.to_csv(
    FINAL_MITIGATION_CSV,
    index=False
)

# ---------------------------------------------------------------------------
# Verify file
# ---------------------------------------------------------------------------

file_exists = FINAL_MITIGATION_CSV.exists()

if file_exists:
    file_size_mb = FINAL_MITIGATION_CSV.stat().st_size / (
        1024 * 1024
    )
else:
    file_size_mb = 0

print("\nFinal mitigation CSV:")
print(f"Path      : {FINAL_MITIGATION_CSV}")
print(f"Exists    : {file_exists}")
print(f"Size      : {file_size_mb:.2f} MB")
print(f"Rows      : {len(final_mitigation_df):,}")
print(f"Columns   : {len(final_mitigation_df.columns)}")

# ---------------------------------------------------------------------------
# Reload verification
# ---------------------------------------------------------------------------

if not file_exists:
    raise FileNotFoundError(
        "Final mitigation CSV was not created successfully."
    )

verification_df = pd.read_csv(FINAL_MITIGATION_CSV)

reload_pass = (
    len(verification_df) == len(final_mitigation_df)
    and list(verification_df.columns)
    == list(final_mitigation_df.columns)
)

print("\nReload verification:")
print(f"Reloaded rows       : {len(verification_df):,}")
print(f"Reloaded columns    : {len(verification_df.columns)}")
print(f"Schema/row count OK : {reload_pass}")

print("\n" + "=" * 80)
print(f"FINAL MITIGATION CSV SAVE : {reload_pass}")
print("=" * 80)

if not reload_pass:
    raise ValueError(
        "Saved mitigation CSV failed reload verification."
    )

================================================================================
SAVING FINAL MITIGATION OUTPUT
================================================================================

Final mitigation CSV:
Path      : /content/drive/MyDrive/Major_Project/mitigation/final_mitigation_results.csv
Exists    : True
Size      : 100.14 MB
Rows      : 338,445
Columns   : 23

Reload verification:
Reloaded rows       : 338,445
Reloaded columns    : 23
Schema/row count OK : True

================================================================================
FINAL MITIGATION CSV SAVE : True
================================================================================

In [19]:
# =============================================================================
# SECTION 7 — SAVE FINAL MITIGATION OUTPUTS
# CELL 3 — Save Mitigation Summary JSON
# =============================================================================

print("=" * 80)
print("SAVING MITIGATION SUMMARY")
print("=" * 80)

# ---------------------------------------------------------------------------
# Output path
# ---------------------------------------------------------------------------

FINAL_MITIGATION_SUMMARY = (
    MITIGATION_DIR / "final_mitigation_summary.json"
)

# ---------------------------------------------------------------------------
# Build final summary
# ---------------------------------------------------------------------------

final_mitigation_summary = {
    "notebook": "07_Mitigation_Engine",

    "input_artifact": str(MITIGATION_INPUT_CSV),

    "output_artifact": str(FINAL_MITIGATION_CSV),

    "total_test_samples": int(total_samples),

    "mitigation_policy": {
        severity: {
            "action": policy["action"],
            "priority": policy["priority"],
            "simulation": policy["simulation"],
        }
        for severity, policy in MITIGATION_POLICY.items()
    },

    "alert_policy": {
        action: {
            "alert_generated": policy["alert_generated"],
            "alert_level": policy["alert_level"],
            "alert_type": policy["alert_type"],
        }
        for action, policy in ALERT_POLICY.items()
    },

    "security_severity_counts": {
        severity: int(count)
        for severity, count in (
            mitigation_df["Security_Severity"]
            .value_counts()
            .to_dict()
            .items()
        )
    },

    "mitigation_action_counts": {
        action: int(count)
        for action, count in (
            mitigation_df["Mitigation_Action"]
            .value_counts()
            .to_dict()
            .items()
        )
    },

    "alert_statistics": {
        "alerts_generated": int(total_alerts),
        "no_alert_required": int(total_no_alert),
        "alert_rate_percent": float(
            percentage(total_alerts, total_samples)
        ),
    },

    "simulation_statistics": {
        "simulated_blocking": int(total_blocked),
        "simulated_rate_limiting": int(total_rate_limited),
        "simulated_monitoring": int(total_monitored),
        "investigations_required": int(total_investigated),

        "simulated_blocking_rate_percent": float(
            percentage(total_blocked, total_samples)
        ),

        "rate_limiting_rate_percent": float(
            percentage(total_rate_limited, total_samples)
        ),

        "monitoring_rate_percent": float(
            percentage(total_monitored, total_samples)
        ),

        "investigation_rate_percent": float(
            percentage(total_investigated, total_samples)
        ),
    },

    "output_schema": FINAL_OUTPUT_COLUMNS,
}

# ---------------------------------------------------------------------------
# Save JSON
# ---------------------------------------------------------------------------

with open(FINAL_MITIGATION_SUMMARY, "w") as f:
    json.dump(
        final_mitigation_summary,
        f,
        indent=4
    )

# ---------------------------------------------------------------------------
# Verify saved JSON
# ---------------------------------------------------------------------------

summary_exists = FINAL_MITIGATION_SUMMARY.exists()

print("\nFinal mitigation summary:")
print(f"Path   : {FINAL_MITIGATION_SUMMARY}")
print(f"Exists : {summary_exists}")

if not summary_exists:
    raise FileNotFoundError(
        "Final mitigation summary JSON was not created."
    )

# ---------------------------------------------------------------------------
# Reload verification
# ---------------------------------------------------------------------------

with open(FINAL_MITIGATION_SUMMARY, "r") as f:
    verification_summary = json.load(f)

summary_reload_pass = (
    verification_summary["total_test_samples"]
    == total_samples
    and verification_summary["output_schema"]
    == FINAL_OUTPUT_COLUMNS
)

print("\nReload verification:")
print(
    f"Total samples verified : "
    f"{verification_summary['total_test_samples']:,}"
)
print(
    f"Schema verified        : "
    f"{verification_summary['output_schema'] == FINAL_OUTPUT_COLUMNS}"
)
print(
    f"Summary reload PASS    : "
    f"{summary_reload_pass}"
)

print("\n" + "=" * 80)
print(f"MITIGATION SUMMARY SAVE : {summary_reload_pass}")
print("=" * 80)

if not summary_reload_pass:
    raise ValueError(
        "Saved mitigation summary failed reload verification."
    )

================================================================================
SAVING MITIGATION SUMMARY
================================================================================

Final mitigation summary:
Path   : /content/drive/MyDrive/Major_Project/mitigation/final_mitigation_summary.json
Exists : True

Reload verification:
Total samples verified : 338,445
Schema verified        : True
Summary reload PASS    : True

================================================================================
MITIGATION SUMMARY SAVE : True
================================================================================

# Section 8

In [20]:
# =============================================================================
# SECTION 8 — FINAL VERIFICATION
# CELL 1 — Verify Final Mitigation Artifacts
# =============================================================================

print("=" * 80)
print("FINAL MITIGATION ARTIFACT VERIFICATION")
print("=" * 80)

# ---------------------------------------------------------------------------
# Expected final artifacts
# ---------------------------------------------------------------------------

EXPECTED_FINAL_CSV = (
    MITIGATION_DIR / "final_mitigation_results.csv"
)

EXPECTED_FINAL_JSON = (
    MITIGATION_DIR / "final_mitigation_summary.json"
)

# ---------------------------------------------------------------------------
# 1. File existence
# ---------------------------------------------------------------------------

csv_exists = EXPECTED_FINAL_CSV.exists()
json_exists = EXPECTED_FINAL_JSON.exists()

print("\n1. Artifact Existence")
print("-" * 80)

print(f"Final CSV exists  : {csv_exists}")
print(f"Final JSON exists : {json_exists}")

# ---------------------------------------------------------------------------
# 2. Load final CSV
# ---------------------------------------------------------------------------

verified_final_df = pd.read_csv(
    EXPECTED_FINAL_CSV
)

print("\n2. Final CSV")
print("-" * 80)

print(f"Rows    : {len(verified_final_df):,}")
print(f"Columns : {len(verified_final_df.columns)}")

# ---------------------------------------------------------------------------
# 3. Required columns
# ---------------------------------------------------------------------------

missing_columns = [
    column
    for column in FINAL_OUTPUT_COLUMNS
    if column not in verified_final_df.columns
]

column_check = (
    len(missing_columns) == 0
    and list(verified_final_df.columns)
    == FINAL_OUTPUT_COLUMNS
)

print(f"Missing columns : {missing_columns}")
print(f"Column check    : {column_check}")

# ---------------------------------------------------------------------------
# 4. Row count
# ---------------------------------------------------------------------------

row_count_check = (
    len(verified_final_df) == 338_445
)

print(f"Row count check : {row_count_check}")

# ---------------------------------------------------------------------------
# 5. Test_Index integrity
# ---------------------------------------------------------------------------

test_index_check = (
    verified_final_df["Test_Index"].nunique() == 338_445
    and verified_final_df["Test_Index"].iloc[0] == 0
    and verified_final_df["Test_Index"].iloc[-1] == 338_444
)

print(f"Test_Index check: {test_index_check}")

# ---------------------------------------------------------------------------
# 6. Required-value completeness
# ---------------------------------------------------------------------------

required_value_columns = [
    "Test_Index",
    "Predicted_Label",
    "AnomalyFlow_Score",
    "Decision_State",
    "Security_Severity",
    "Mitigation_Action",
    "Mitigation_Priority",
    "Alert_Generated",
    "Alert_Level",
    "Alert_Type",
    "Mitigation_Outcome",
]

missing_value_counts = (
    verified_final_df[required_value_columns]
    .isna()
    .sum()
)

total_missing_required = int(
    missing_value_counts.sum()
)

missing_value_check = (
    total_missing_required == 0
)

print(f"Missing required values : {total_missing_required}")
print(f"Missing-value check     : {missing_value_check}")

# ---------------------------------------------------------------------------
# 7. Load and verify final JSON
# ---------------------------------------------------------------------------

with open(EXPECTED_FINAL_JSON, "r") as f:
    verified_summary = json.load(f)

json_sample_count_check = (
    verified_summary["total_test_samples"]
    == 338_445
)

json_schema_check = (
    verified_summary["output_schema"]
    == FINAL_OUTPUT_COLUMNS
)

print("\n3. Final JSON")
print("-" * 80)

print(
    f"Total samples check : "
    f"{json_sample_count_check}"
)

print(
    f"Schema check        : "
    f"{json_schema_check}"
)

# ---------------------------------------------------------------------------
# Overall verification
# ---------------------------------------------------------------------------

final_artifact_verification = (
    csv_exists
    and json_exists
    and column_check
    and row_count_check
    and test_index_check
    and missing_value_check
    and json_sample_count_check
    and json_schema_check
)

print("\n" + "=" * 80)
print(
    f"FINAL ARTIFACT VERIFICATION : "
    f"{final_artifact_verification}"
)
print("=" * 80)

if not final_artifact_verification:
    raise ValueError(
        "One or more final mitigation artifact checks failed."
    )

================================================================================
FINAL MITIGATION ARTIFACT VERIFICATION
================================================================================

1. Artifact Existence
--------------------------------------------------------------------------------
Final CSV exists  : True
Final JSON exists : True

2. Final CSV
--------------------------------------------------------------------------------
Rows    : 338,445
Columns : 23
Missing columns : []
Column check    : True
Row count check : True
Test_Index check: True
Missing required values : 0
Missing-value check     : True

3. Final JSON
--------------------------------------------------------------------------------
Total samples check : True
Schema check        : True

================================================================================
FINAL ARTIFACT VERIFICATION : True
================================================================================

In [21]:
# =============================================================================
# SECTION 8 — FINAL VERIFICATION
# CELL 2 — Final Decision and Mitigation Consistency Check
# =============================================================================

print("=" * 80)
print("FINAL DECISION & MITIGATION CONSISTENCY VERIFICATION")
print("=" * 80)

# ---------------------------------------------------------------------------
# Expected Notebook 06 severity distribution
# ---------------------------------------------------------------------------

expected_severity_counts = {
    "LOW": 261_669,
    "MEDIUM": 36_607,
    "HIGH": 30_736,
    "NORMAL": 8_692,
    "MONITOR": 693,
    "INVESTIGATE": 48,
}

# ---------------------------------------------------------------------------
# Actual severity distribution from saved final artifact
# ---------------------------------------------------------------------------

actual_severity_counts = (
    verified_final_df["Security_Severity"]
    .value_counts()
    .to_dict()
)

severity_check = (
    actual_severity_counts == expected_severity_counts
)

print("\n1. Security Severity Consistency")
print("-" * 80)

for severity, expected_count in expected_severity_counts.items():
    actual_count = actual_severity_counts.get(severity, 0)

    print(
        f"{severity:<15}"
        f"Expected: {expected_count:>8,} | "
        f"Actual: {actual_count:>8,} | "
        f"PASS: {actual_count == expected_count}"
    )

print(f"\nSeverity distribution check : {severity_check}")

# ---------------------------------------------------------------------------
# Expected mitigation action distribution
# ---------------------------------------------------------------------------

expected_mitigation_actions = {
    "ALERT_AND_LOG": 261_669,
    "RATE_LIMIT": 36_607,
    "BLOCK_AND_RATE_LIMIT": 30_736,
    "NO_ACTION": 8_692,
    "MONITOR": 693,
    "INVESTIGATE": 48,
}

actual_mitigation_actions = (
    verified_final_df["Mitigation_Action"]
    .value_counts()
    .to_dict()
)

mitigation_action_check = (
    actual_mitigation_actions == expected_mitigation_actions
)

print("\n2. Mitigation Action Consistency")
print("-" * 80)

for action, expected_count in expected_mitigation_actions.items():
    actual_count = actual_mitigation_actions.get(action, 0)

    print(
        f"{action:<24}"
        f"Expected: {expected_count:>8,} | "
        f"Actual: {actual_count:>8,} | "
        f"PASS: {actual_count == expected_count}"
    )

print(
    f"\nMitigation action check : "
    f"{mitigation_action_check}"
)

# ---------------------------------------------------------------------------
# Verify blocking count
# ---------------------------------------------------------------------------

expected_blocking = 30_736

actual_blocking = int(
    verified_final_df["Simulated_Block"].sum()
)

blocking_check = (
    actual_blocking == expected_blocking
)

print("\n3. Simulated Blocking Consistency")
print("-" * 80)

print(f"Expected blocking samples : {expected_blocking:,}")
print(f"Actual blocking samples   : {actual_blocking:,}")
print(f"PASS                      : {blocking_check}")

# ---------------------------------------------------------------------------
# Verify rate-limiting count
# ---------------------------------------------------------------------------

expected_rate_limiting = 67_343

actual_rate_limiting = int(
    verified_final_df["Simulated_Rate_Limit"].sum()
)

rate_limiting_check = (
    actual_rate_limiting == expected_rate_limiting
)

print("\n4. Simulated Rate-Limiting Consistency")
print("-" * 80)

print(f"Expected rate-limited samples : {expected_rate_limiting:,}")
print(f"Actual rate-limited samples   : {actual_rate_limiting:,}")
print(f"PASS                          : {rate_limiting_check}")

# ---------------------------------------------------------------------------
# Verify alert count
# ---------------------------------------------------------------------------

expected_alerts = 329_753

actual_alerts = int(
    verified_final_df["Alert_Generated"].sum()
)

alert_check = (
    actual_alerts == expected_alerts
)

print("\n5. Alert Consistency")
print("-" * 80)

print(f"Expected alerts : {expected_alerts:,}")
print(f"Actual alerts   : {actual_alerts:,}")
print(f"PASS            : {alert_check}")

# ---------------------------------------------------------------------------
# Verify mitigation outcomes
# ---------------------------------------------------------------------------

outcome_counts = (
    verified_final_df["Mitigation_Outcome"]
    .value_counts()
    .to_dict()
)

expected_outcomes = {
    "ALERT_LOGGED": 261_669,
    "RATE_LIMIT_SIMULATED": 36_607,
    "BLOCK_AND_RATE_LIMIT_SIMULATED": 30_736,
    "NO_ACTION_REQUIRED": 8_692,
    "MONITORING_ACTIVE": 693,
    "INVESTIGATION_REQUIRED": 48,
}

outcome_check = (
    outcome_counts == expected_outcomes
)

print("\n6. Mitigation Outcome Consistency")
print("-" * 80)

for outcome, expected_count in expected_outcomes.items():
    actual_count = outcome_counts.get(outcome, 0)

    print(
        f"{outcome:<34}"
        f"Expected: {expected_count:>8,} | "
        f"Actual: {actual_count:>8,} | "
        f"PASS: {actual_count == expected_count}"
    )

print(f"\nOutcome check : {outcome_check}")

# ---------------------------------------------------------------------------
# Overall consistency verification
# ---------------------------------------------------------------------------

final_consistency_check = (
    severity_check
    and mitigation_action_check
    and blocking_check
    and rate_limiting_check
    and alert_check
    and outcome_check
)

print("\n" + "=" * 80)
print(
    f"FINAL CONSISTENCY VERIFICATION : "
    f"{final_consistency_check}"
)
print("=" * 80)

if not final_consistency_check:
    raise ValueError(
        "Final mitigation consistency verification failed."
    )

================================================================================
FINAL DECISION & MITIGATION CONSISTENCY VERIFICATION
================================================================================

1. Security Severity Consistency
--------------------------------------------------------------------------------
LOW            Expected:  261,669 | Actual:  261,669 | PASS: True
MEDIUM         Expected:   36,607 | Actual:   36,607 | PASS: True
HIGH           Expected:   30,736 | Actual:   30,736 | PASS: True
NORMAL         Expected:    8,692 | Actual:    8,692 | PASS: True
MONITOR        Expected:      693 | Actual:      693 | PASS: True
INVESTIGATE    Expected:       48 | Actual:       48 | PASS: True

Severity distribution check : True

2. Mitigation Action Consistency
--------------------------------------------------------------------------------
ALERT_AND_LOG           Expected:  261,669 | Actual:  261,669 | PASS: True
RATE_LIMIT              Expected:   36,607 | Actual:   36,607 | PASS: True
BLOCK_AND_RATE_LIMIT    Expected:   30,736 | Actual:   30,736 | PASS: True
NO_ACTION               Expected:    8,692 | Actual:    8,692 | PASS: True
MONITOR                 Expected:      693 | Actual:      693 | PASS: True
INVESTIGATE             Expected:       48 | Actual:       48 | PASS: True

Mitigation action check : True

3. Simulated Blocking Consistency
--------------------------------------------------------------------------------
Expected blocking samples : 30,736
Actual blocking samples   : 30,736
PASS                      : True

4. Simulated Rate-Limiting Consistency
--------------------------------------------------------------------------------
Expected rate-limited samples : 67,343
Actual rate-limited samples   : 67,343
PASS                          : True

5. Alert Consistency
--------------------------------------------------------------------------------
Expected alerts : 329,753
Actual alerts   : 329,753
PASS            : True

6. Mitigation Outcome Consistency
--------------------------------------------------------------------------------
ALERT_LOGGED                      Expected:  261,669 | Actual:  261,669 | PASS: True
RATE_LIMIT_SIMULATED              Expected:   36,607 | Actual:   36,607 | PASS: True
BLOCK_AND_RATE_LIMIT_SIMULATED    Expected:   30,736 | Actual:   30,736 | PASS: True
NO_ACTION_REQUIRED                Expected:    8,692 | Actual:    8,692 | PASS: True
MONITORING_ACTIVE                 Expected:      693 | Actual:      693 | PASS: True
INVESTIGATION_REQUIRED            Expected:       48 | Actual:       48 | PASS: True

Outcome check : True

================================================================================
FINAL CONSISTENCY VERIFICATION : True
================================================================================